---
- name: PostgreSQL | Install Client | Add Repository | Gather Facts
  ansible.builtin.setup:

- name: PostgreSQL | Install Client | Add Repository | Install Required Packages
  ansible.builtin.apt:
      package:
          - curl
          - ca-certificates
          - locales
          - python3-debian
          - python3-requests
          - ssl-cert
      state: present
      update_cache: true

- name: PostgreSQL | Install Client | Add Repository | Remove Default PostgreSQL Package Is Exists
  ansible.builtin.apt:
      name:
          - postgresql
          - postgresql-client
          - postgresql-contrib
      state: absent
      purge: true

- name: PostgreSQL | Install Client | Add Repository | Create PostgreSQL-Common Directory
  when: false
  ansible.builtin.file:
      path: /usr/share/postgresql-common/pgdg
      state: directory
      owner: root
      group: root
      mode: "0755"

- name: PostgreSQL | Install Client | Add Repository | Download GPG Key
  when: false
  ansible.builtin.get_url:
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
      dest: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
      mode: "0644"
      checksum: "sha256:0144068502a1eddd2a0280ede10ef607d1ec592ce819940991203941564e8e76"
      owner: root
      group: root

- name: PostgreSQL | Install Client | Add Repository | Get System Architecture From Dpkg
  ansible.builtin.command:
      argv:
          - dpkg
          - --print-architecture
  register: postgresql_machine_architecture_shell
  changed_when: false

- name: PostgreSQL | Install Client | Add Repository | Remove Pgdg List File
  ansible.builtin.file:
      path: /etc/apt/sources.list.d/pgdg.list
      state: absent

- name: PostgreSQL | Install Client | Add Repository | Add APT deb822_repository
  ansible.builtin.deb822_repository:
      name: pgdg
      allow_downgrade_to_insecure: false
      allow_insecure: false
      # signed_by: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
      signed_by: "{{ postgresql_pgp_asc_content }}"
      architectures:
          - "{{ postgresql_machine_architecture_shell.stdout }}"
      suites:
          - "{{ ansible_facts.distribution_release }}-pgdg"
      uris:
          - https://apt.postgresql.org/pub/repos/apt
      types:
          - deb
      components:
          - main
      trusted: true
      enabled: true
      mode: "0644"
      state: present
      check_valid_until: true
      check_date: true

- name: PostgreSQL | Install Client | Add Repository | APT Update Cache
  ansible.builtin.apt:
      update_cache: true
