---
- name: PostgreSQL | Install Client | Add Repository
  ansible.builtin.import_tasks: add-repo.yml

- name: PostgreSQL | Install Client | Install Packages
  ansible.builtin.apt:
      name:
          - postgresql-client-{{ postgresql_version }}
          - python3-psycopg2
          - libpq-dev
      state: present
      update_cache: true
