---
- name: NodeJS | Molecule | Verify
  hosts: all
  gather_facts: false
  tasks:
      - name: NodeJS | Molecule | Verify | Import Roles for variables
        ansible.builtin.import_role:
            name: arpanrec.nebula.nodejs
            tasks_from: prerequisites

      - name: NodeJS | Molecule | Verify | Set nodejs version details
        ansible.builtin.set_fact:
            nodejs_version_details: "{{ lookup('arpanrec.nebula.version_db', 'nodejs',
                nodejs_rv_version=nodejs_rv_version) | from_json }}"

      - name: NodeJS | Molecule | Verify | Get node version from shell
        ansible.builtin.command: node --version
        environment:
            PATH: "{{ nodejs_rv_install_path }}/bin:{{ ansible_env.PATH }}"
        register: nodejs_rv_version_shell_result
        changed_when: false

      - name: NodeJS | Molecule | Verify | Fail if nodejs version is not present
        ansible.builtin.assert:
            that: nodejs_rv_version_shell_result.stdout == nodejs_version_details.version
            success_msg: NodeJS Version {{ nodejs_version_details.version }} is installed
            fail_msg: "NodeJS Version {{ nodejs_version_details.version }} is not installed, \
                Shell result {{ nodejs_rv_version_shell_result.stdout }}"
