---
- name: Bitwarden Secrets Manager SDK | Molecule | Converge
  hosts: all
  gather_facts: false
  tasks:
      - name: Bitwarden Secrets Manager SDK | Molecule | Converge | Import role
        ansible.builtin.import_role:
            name: arpanrec.nebula.bws
