---
- name: Bitwarden Secrets Manager SDK | Molecule | Verify
  hosts: all
  gather_facts: true
  become: false
  tasks:
      - name: Bitwarden Secrets Manager SDK | Molecule | Verify | Import Roles for variables
        ansible.builtin.import_role:
            name: arpanrec.nebula.bws
            tasks_from: prerequisites

      - name: Bitwarden Secrets Manager SDK | Get Version Details
        ansible.builtin.set_fact:
            bws_sdk_version_details: "{{ lookup('arpanrec.nebula.version_db', 'bws',
                bws_sdk_version_tag=bws_sdk_version_tag) | from_json }}"

      - name: Bitwarden Secrets Manager SDK | Molecule | Verify | Get bw version from shell
        ansible.builtin.command: bws --version
        environment:
            PATH: "{{ bws_sdk_bin_dir }}:{{ ansible_env.PATH }}"
        register: bws_sdk_cli_rv_tmp_version_shell_result
        changed_when: false

      - name: Bitwarden Secrets Manager SDK | Molecule | Verify | Fail if bw version is not present
        ansible.builtin.assert:
            that: bws_sdk_cli_rv_tmp_version_shell_result.stdout is match("bws " + bws_sdk_version_details.version[5:] )
            success_msg: BWS Version {{ bws_sdk_version_details.version }} is installed
            fail_msg: >-
                BWS Version {{ bws_sdk_version_details.version }} is not installed,
                Shell result {{ bws_sdk_cli_rv_tmp_version_shell_result.stdout }}
