---
- name: Hadolint | Molecule | Verify
  hosts: all
  gather_facts: false
  tasks:
      - name: Hadolint | Molecule | Verify | Import Roles for variables
        ansible.builtin.import_role:
            name: arpanrec.nebula.hadolint
            tasks_from: prerequisites

      - name: Hadolint | Molecule | Get Release
        ansible.builtin.set_fact:
            hadolint_version_details: "{{ lookup('arpanrec.nebula.version_db', 'hadolint',
                hadolint_rv_version=hadolint_rv_version) | from_json }}"

      - name: Hadolint | Molecule | Verify | Get hadolint version from shell
        ansible.builtin.command:
            argv:
                - hadolint
                - --version
        environment:
            PATH: "{{ hadolint_rv_install_path }}:{{ ansible_env.PATH }}"
        register: hadolint_rv_version_shell_result
        changed_when: false

      - name: Hadolint | Molecule | Verify | Fail if hadolint version is not present
        ansible.builtin.assert:
            that: "hadolint_version_details.version[1:] == hadolint_rv_version_shell_result.stdout_lines[0] \
                | split | last"
            success_msg: Hadolint Version {{ hadolint_version_details.version }} is installed
            fail_msg: Hadolint Version {{ hadolint_version_details.version }} is not installed,
                Shell result {{ hadolint_rv_version_shell_result.stdout }}
