---
- name: Terminal | Terminal Themes | Initialize p10k gitstatus
  block:
      - name: Terminal | Terminal Themes | Initialize p10k gitstatus | Execute install script
        ansible.builtin.shell: |
            set timeout 100
            {{ terminal_rv_user_home_dir }}/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install -f
        changed_when: true
        register: pv_ua_tmp_p10k_shell_install_result

- name: Terminal | Terminal Themes | Initialize fzf
  block:
      - name: Terminal | Terminal Themes | Initialize fzf | Execute install script
        ansible.builtin.shell: |
            set timeout 100
            {{ terminal_rv_user_home_dir }}/.fzf/install --all
        changed_when: true
        register: pv_ua_tmp_fzf_shell_install_result
