---
namespace: arpanrec
name: nebula
version: 1.11.5
readme: README.md
authors:
    - "Arpan Mandal <arpan.rec@gmail.com>"
description: common ansible resources
repository: https://github.com/arpanrec/arpanrec.nebula.git
license_file: LICENSE
issues: https://github.com/arpanrec/arpanrec.nebula/issues
# dependencies:
#   "https://github.com/ansible-collections/community.general.git": "6.0.1"
#   "https://github.com/ansible-collections/ansible.posix.git": "1.4.0"
#   "https://github.com/ansible-collections/community.docker.git": "3.3.1"
homepage: "https://github.com/arpanrec/arpanrec.nebula"
documentation: https://github.com/arpanrec/arpanrec.nebula/blob/main/README.md
build_ignore:
    - ".ansible-lint"
    - ".git"
    - ".gitattributes"
    - ".github"
    - ".gitignore"
    - ".gitkeep"
    - ".idea"
    - ".mypy_cache"
    - ".py.typed"
    - ".pylintrc"
    - ".trunk"
    - ".venv"
    - ".vscode"
    - ".yamllint"
    - "CODE_OF_CONDUCT.md"
    - "DEVELOPMENT.md"
    - "build"
    - "molecule"
    - "node_modules"
    - "poetry.lock"
    - "pyproject.toml"
    - "requirements-dev.txt"
    - "requirements.txt"
    - "requirements.yml"
    - "venv"
tags:
    - "linux"
    - "debian"
