---
namespace: arpanrec
name: nebula
version: 1.14.47
readme: README.md
authors:
    - "Arpan <me@arpanrec.com>"
description: common ansible resources
repository: https://github.com/arpanrec/arpanrec.nebula.git
license_file: LICENSE
issues: https://github.com/arpanrec/arpanrec.nebula/issues
dependencies:
    community.general: 11.4.0
    community.crypto: 3.0.4
    ansible.posix: 2.1.0
    community.postgresql: 4.1.0
homepage: "https://github.com/arpanrec/arpanrec.nebula"
documentation: https://github.com/arpanrec/arpanrec.nebula/blob/main/README.md
build_ignore:
    - ".ansible-lint"
    - ".git"
    - ".gitattributes"
    - ".github"
    - ".gitignore"
    - ".gitkeep"
    - ".idea"
    - ".mypy_cache"
    - ".py.typed"
    - ".pylintrc"
    - ".trunk"
    - ".venv"
    - ".vscode"
    - ".yamllint"
    - "CODE_OF_CONDUCT.md"
    - "DEVELOPMENT.md"
    - "build"
    - "molecule"
    - "node_modules"
    - "package.json"
    - "pnpm-lock.yaml"
    - "uv.lock"
    - "pyproject.toml"
    - "requirements-dev.txt"
    - "requirements.txt"
    - "requirements.yml"
    - "venv"
    - ".ansible"
    - "roles/geerlingguy.docker"
    - "dest"
    - ".prettierignore"
tags:
    - "linux"
    - "debian"
