[tool.mypy]
python_version = "3.12"
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = false
check_untyped_defs = true
disallow_any_generics = true
disallow_untyped_calls = true
disallow_untyped_defs = true
no_implicit_optional = true
exclude = ["^.venv/.*"]

[tool.pylint.main]
py-version = "3.12"
jobs = 0
ignore-paths = ["^\\.venv/.*"]
ignore = [".venv"]

[tool.pylint.format]
max-line-length = 120
indent-string = "    "

[tool.pylint.design]
max-args = 8
max-positional-arguments = 8
max-locals = 20
max-returns = 8

[tool.pylint."messages control"]
disable = ["duplicate-code", "W0511"]

[tool.uv]
link-mode = "clone"
package = false
required-version = ">=0.12.8,<1.0"
system-certs = true

[[tool.uv.index]]
default = true
name = "pypi_remote"
url = "https://pypi.org/simple/"

[tool.isort]
profile = "black"
line_length = 120

[tool.black]
line-length = 120
target-version = ["py312"]

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "W", "B", "UP", "SIM", "C4"]

[tool.pyright]
include = ["plugins"]
pythonVersion = "3.12"
venvPath = "."
venv = ".venv"
typeCheckingMode = "strict"

[project]
name = "arpanrec-nebula"
version = "1.19.0"
description = "common ansible resources"
readme = "README.md"
requires-python = ">=3.12.0"
dependencies = [
    "ansible==14.4.0",
    "cachier==4.2.0",
    "passlib==1.7.4",
    "httpx==0.28.1",
]
license-files = ["LICENSE"]

[[project.authors]]
name = "Arpan Mandal"
email = "me@arpanrec.com"

[dependency-groups]
dev = [
    "black==26.5.1",
    "docker==7.2.0",
    "isort==9.0.1",
    "molecule==26.9.0",
    "molecule-plugins==26.7.15",
    "mypy==2.3.1",
    "neovim==0.3.1",
    "pylint==4.0.9",
    "pyright==1.1.414",
    "ruff==0.16.9",
    "types-pyyaml==6.0.12.20260906",
    "yamllint==1.38.0",
    "ansible-lint==26.9.0",
    "antsibull-docs==2.27.0",
]
