---
collections:
    - name: community.general
      version: 10.2.0
    - name: community.crypto
      version: 2.23.0
    - name: amazon.aws
      version: 9.1.1
    - name: community.docker
      version: 4.3.0
    - name: ansible.posix
      version: 2.0.0
    - name: kewlfft.aur
      version: 0.11.1
roles:
    - name: geerlingguy.docker
      version: 7.4.4
