---
roles:
    - name: geerlingguy.docker
      scm: git
      src: https://github.com/geerlingguy/ansible-role-docker.git
      version: 8.0.0
collections:
    - name: community.general
      source: https://github.com/ansible-collections/community.general.git
      type: git
      version: 13.4.0
    - name: community.crypto
      source: https://github.com/ansible-collections/community.crypto.git
      type: git
      version: 3.4.0
    - name: ansible.posix
      source: https://github.com/ansible-collections/ansible.posix.git
      type: git
      version: 2.2.2
    - name: community.postgresql
      source: https://github.com/ansible-collections/community.postgresql.git
      type: git
      version: 5.0.0
