---
collections:
    - name: community.general
      version: 11.2.1
    - name: community.crypto
      version: 3.0.3
    - name: amazon.aws
      version: 10.1.1
    - name: community.docker
      version: 4.7.0
    - name: ansible.posix
      version: 2.1.0
    - name: kewlfft.aur
      version: 0.11.1
roles:
    - name: geerlingguy.docker
      version: 7.5.1
