---
roles:
    - name: geerlingguy.docker
      version: 8.0.0
collections:
    - name: community.general
      version: 13.0.1
    - name: community.crypto
      version: 3.2.1
    - name: ansible.posix
      version: 2.2.0
    - name: community.postgresql
      version: 4.2.0
