---
collections:
    - name: community.general
      version: 11.0.0
    - name: community.crypto
      version: 2.26.3
    - name: amazon.aws
      version: 10.1.0
    - name: community.docker
      version: 4.6.1
    - name: ansible.posix
      version: 2.0.0
    - name: kewlfft.aur
      version: 0.11.1
roles:
    - name: geerlingguy.docker
      version: 7.4.7
