---
- name: Get Certificate Ownca | Certificate To Be Created | When Certificate Content Not Present
  when: not get_certificate_ownca_rv_getcert_to_be_created
  ansible.builtin.set_fact:
    get_certificate_ownca_rv_getcert_to_be_created: "{{ get_certificate_ownca_rv_getcert_certificate_content | length < 2 }}"
    get_certificate_ownca_rv_getcert_to_be_created_reason: "When Certificate Content Not Present"

- name: Get Certificate Ownca | Certificate To Be Created | Get Certificate Old Information
  when: not get_certificate_ownca_rv_getcert_to_be_created
  community.crypto.x509_certificate_info:
    content: "{{ get_certificate_ownca_rv_getcert_certificate_content }}"
    valid_at:
      one_day_after: "+1d"
  register: get_certificate_ownca_rv_getcert_tmp_certificate_content_x509_info
  ignore_errors: true

- name: Get Certificate Ownca | Certificate To Be Created | Existing Certificate is Invalid
  when: not get_certificate_ownca_rv_getcert_to_be_created
  ansible.builtin.set_fact:
    get_certificate_ownca_rv_getcert_to_be_created: >-
      {{ get_certificate_ownca_rv_getcert_tmp_certificate_content_x509_info.failed is defined
      and
      get_certificate_ownca_rv_getcert_tmp_certificate_content_x509_info.failed }}
    get_certificate_ownca_rv_getcert_to_be_created_reason: "Existing Certificate is Invalid"

- name: Get Certificate Ownca | Certificate To Be Created | Get Issuer Information
  community.crypto.x509_certificate_info:
    content: "{{ get_certificate_ownca_rv_certificate_content }}"
    valid_at:
      not_crossed_issuer: "+{{ get_certificate_ownca_rv_getcert_validity_days }}d"
  register: get_certificate_ownca_rv_getcert_tmp_owca_certificate_content_x509_info

- name: Get Certificate Ownca | Certificate To Be Created | Fail if crossed the validity of CA
  ansible.builtin.fail:
    msg: "Expected validity should not cross CA"
  when: not get_certificate_ownca_rv_getcert_tmp_owca_certificate_content_x509_info.valid_at.not_crossed_issuer

- name:
    Get Certificate Ownca | Certificate To Be Created | Authority Key Identifier Mismatch,
    Existing Certificate is not signed by OwnCA
  when: not get_certificate_ownca_rv_getcert_to_be_created
  ansible.builtin.set_fact:
    get_certificate_ownca_rv_getcert_to_be_created: >-
      {{ get_certificate_ownca_rv_getcert_tmp_certificate_content_x509_info.authority_key_identifier
      !=
      get_certificate_ownca_rv_getcert_tmp_owca_certificate_content_x509_info.subject_key_identifier }}
    get_certificate_ownca_rv_getcert_to_be_created_reason: "Authority Key Identifier Mismatch, Existing Certificate is not signed by OwnCA"

- name: Get Certificate Ownca | Certificate To Be Created | Certificate Expired
  when: not get_certificate_ownca_rv_getcert_to_be_created
  ansible.builtin.set_fact:
    get_certificate_ownca_rv_getcert_to_be_created: "{{ not get_certificate_ownca_rv_getcert_tmp_certificate_content_x509_info.valid_at.one_day_after }}"
    get_certificate_ownca_rv_getcert_to_be_created_reason: "Certificate Expired"

- name: Get Certificate Ownca | Certificate To Be Created | Create a dummy CSR for key uses
  when: not get_certificate_ownca_rv_getcert_to_be_created
  changed_when: false
  community.crypto.openssl_csr_pipe:
    privatekey_content: "{{ get_certificate_ownca_rv_getcert_private_key_content }}"
    privatekey_passphrase: "{{ get_certificate_ownca_rv_getcert_private_key_password | default(omit, True) }}"
    key_usage: "{{ get_certificate_ownca_rv_getcert_key_usage | default(omit, True) }}"
    extended_key_usage: "{{ get_certificate_ownca_rv_getcert_extended_key_usage | default(omit, True) }}"
  register: get_certificate_ownca_rv_getcert_tmp_to_be_created_csr_for_keyusage

- name: Get Certificate Ownca | Certificate To Be Created | Key Usage Mismatch
  when: not get_certificate_ownca_rv_getcert_to_be_created
  ansible.builtin.set_fact:
    get_certificate_ownca_rv_getcert_to_be_created: "{{ expected_list | difference(current_list) | length != 0 or current_list | difference(expected_list) | length != 0 }}"
    get_certificate_ownca_rv_getcert_to_be_created_reason: "Key Usage Mismatch"
  vars:
    current_list: "{{ get_certificate_ownca_rv_getcert_tmp_certificate_content_x509_info.key_usage | default([]) }}"
    expected_list: "{{ get_certificate_ownca_rv_getcert_tmp_to_be_created_csr_for_keyusage.diff.after.key_usage | default([]) }}"

- name: Get Certificate Ownca | Certificate To Be Created | Extended Key Usage Mismatch
  when: not get_certificate_ownca_rv_getcert_to_be_created
  ansible.builtin.set_fact:
    get_certificate_ownca_rv_getcert_to_be_created: "{{ expected_list | difference(current_list) | length != 0 or current_list | difference(expected_list) | length != 0 }}"
    get_certificate_ownca_rv_getcert_to_be_created_reason: "Extended Key Usage Mismatch"
  vars:
    current_list: "{{ get_certificate_ownca_rv_getcert_tmp_certificate_content_x509_info.extended_key_usage | default([]) }}"
    expected_list: "{{ get_certificate_ownca_rv_getcert_tmp_to_be_created_csr_for_keyusage.diff.after.extended_key_usage | default([]) }}"

- name: Get Certificate Ownca | Certificate To Be Created | SAN Mismatch
  when: not get_certificate_ownca_rv_getcert_to_be_created
  ansible.builtin.set_fact:
    get_certificate_ownca_rv_getcert_to_be_created: "{{ expected_list | difference(current_list) | length != 0 or current_list | difference(expected_list) | length != 0 }}"
    get_certificate_ownca_rv_getcert_to_be_created_reason: "SAN Mismatch"
  vars:
    current_list: "{{ get_certificate_ownca_rv_getcert_tmp_certificate_content_x509_info.subject_alt_name | default([]) }}"
    expected_list: "{{ get_certificate_ownca_rv_getcert_subject_alt_name | default([]) }}"

- name: Get Certificate Ownca | Certificate To Be Created | Subject Mismatch
  when: not get_certificate_ownca_rv_getcert_to_be_created
  ansible.builtin.set_fact:
    get_certificate_ownca_rv_getcert_to_be_created: "{{ get_certificate_ownca_rv_getcert_tmp_certificate_content_x509_info.subject != get_certificate_ownca_rv_getcert_subject_user_default }}"
    get_certificate_ownca_rv_getcert_to_be_created_reason: "Subject Mismatch"
  vars:
    get_certificate_ownca_rv_getcert_subject_user_default: "{{ get_certificate_ownca_rv_getcert_subject | default({}) }}"

- name: Get Certificate Ownca | Certificate To Be Created | Basic Constraints Mismatch
  when: not get_certificate_ownca_rv_getcert_to_be_created
  ansible.builtin.set_fact:
    get_certificate_ownca_rv_getcert_to_be_created: "{{ expected_list | difference(current_list) | length != 0 or current_list | difference(expected_list) | length != 0 }}"
    get_certificate_ownca_rv_getcert_to_be_created_reason: "Basic Constraints Mismatch"
  vars:
    expected_list: "{{ get_certificate_ownca_rv_getcert_basic_constraints | default([]) }}"
    current_list: "{{ get_certificate_ownca_rv_getcert_tmp_certificate_content_x509_info.basic_constraints | default([]) }}"

- name: Get Certificate Ownca | Certificate To Be Created | Reason
  when: get_certificate_ownca_rv_getcert_to_be_created
  ansible.builtin.debug:
    msg: "Certificate to be created reason: {{ get_certificate_ownca_rv_getcert_to_be_created_reason }}"
