---
- name: Get Certificate Ownca | Create Private Key | Private Key
  community.crypto.openssl_privatekey_pipe:
    content: "{{ get_certificate_ownca_rv_getcert_private_key_content | default(omit, True) }}"
    size: "{{ get_certificate_ownca_rv_getcert_private_key_size | default(omit, True) }}"
    passphrase: "{{ get_certificate_ownca_rv_getcert_private_key_password | default(omit, True) }}"
    cipher: "{{ (get_certificate_ownca_rv_getcert_private_key_password is defined and get_certificate_ownca_rv_getcert_private_key_password | length > 0) | ternary('auto', omit) }}"
  register: get_certificate_ownca_rv_getcert_private_key_content_create_new

- name: Get Certificate Ownca | Create Private Key | Private Key Set Fact
  when: get_certificate_ownca_rv_getcert_private_key_content_create_new.privatekey is defined
  ansible.builtin.set_fact:
    get_certificate_ownca_rv_getcert_private_key_content: "{{ get_certificate_ownca_rv_getcert_private_key_content_create_new.privatekey }}"
