---
# defaults file for host_essentials

linux_patching_rv_upgrade_existing_packages: true

linux_patching_rv_install_devel_packages: true

linux_patching_rv_devel_packages:
    - net-tools
    - telnet
    - vim
    - git
    - jq
    - zsh
    - htop
    - tmux
    - tree
    - neovim
    - python3-neovim
    - luarocks
    - build-essential
    - ninja-build
    - gettext
    - cmake
    - make
    - openssh-client
    - rsync
    - ntfs-3g
    - exfat-fuse

linux_patching_rv_packages:
    - zip
    - unzip
    - tar
    - wget
    - curl
    - ca-certificates
    - sudo
    - systemd
    - gnupg2
    - apt-transport-https
    - locales
    - systemd-timesyncd
    - network-manager
    - gnupg
    - pigz
    - cron
    - acl
    - ufw
    - bzip2
    - procps
    - xz-utils
    # Apt tools
    - apt-utils
    - lsb-release
    - software-properties-common
    # Python tools
    - python3
    - python3-pip
    - python3-venv

linux_patching_rv_managed_packages: []

linux_patching_rv_timezone: Asia/Kolkata

linux_patching_rv_hostname: "{{ ansible_facts['hostname'] | mandatory }}"
# linux_patching_rv_root_ca_pem_content:

linux_patching_rv_ssh_port: 22
