---
# defaults file for host_essentials

linux_patching_rv_upgrade_existing_packages: true

linux_patching_rv_install_headers: true

linux_patching_rv_packages:
    - zip
    - unzip
    - tar
    - wget
    - curl
    - ca-certificates
    - sudo
    - systemd
    - gnupg2
    - apt-transport-https
    - locales
    - systemd-timesyncd
    - network-manager
    - gnupg2
    - gnupg
    - pigz
    - cron
    - acl
    - ufw
    - bzip2

linux_patching_rv_managed_packages: []

linux_patching_rv_timezone: Asia/Kolkata

linux_patching_rv_hostname: "{{ ansible_facts['hostname'] | mandatory }}"
# linux_patching_rv_root_ca_pem_content:

linux_patching_rv_ssh_port: 22
