---
dependency:
    name: galaxy
driver:
    name: docker
platforms:
    - name: debian_role_user_add_docker
      hostname: debian_role_user_add_docker
      image: docker.io/library/debian:bookworm
      pre_build_image: true
provisioner:
    name: ansible
    vvv: false
    env:
        ANSIBLE_VERBOSITY: 1
    playbooks:
        prepare: prepare.yml
        converge: converge.yml
    inventory:
        host_vars:
            debian_role_user_add_docker:
                user_add_rv_username: test
                user_add_rv_password: test
verifier:
    name: ansible
scenario:
    name: role.user_add.docker
    test_sequence:
        - destroy
        - syntax
        - create
        - prepare
        - converge
        - idempotence
        - verify
        - destroy
