---
- name: Application User | Molecule | Prepare
  hosts: all
  gather_facts: false
  tasks:
      - name: Application User | Molecule | Prepare | Bootstrap a host without python installed
        ansible.builtin.raw: apt update && apt install python3 -y
        changed_when: true
