---
# This is an example playbook to execute Ansible tests.

- name: Application User | Molecule | Verify
  hosts: all
  gather_facts: false
  tasks:
      - name: Application User | Molecule | Verify | Get user details
        ansible.builtin.command: "id {{ user_add_rv_username }}"
        register: userdetails
        changed_when: false
