---
- name: Dotfiles | Prerequisites
  ansible.builtin.import_tasks: prerequisites.yml

- name: Dotfiles | Cloning git bare
  ansible.builtin.git:
      single_branch: true
      repo: "{{ dotfiles_rv_git_remote }}"
      dest: "{{ dotfiles_rv_user_home_dir }}/{{ dotfiles_rv_bare_relative_dir }}"
      bare: true
      version: "{{ dotfiles_rv_git_version }}"
  register: pv_ua_dotrepo_update

- name: Dotfiles | Set git config
  ansible.builtin.template:
      src: templates/dotfiles.gitconfig.j2
      dest: "{{ dotfiles_rv_user_home_dir }}/{{ dotfiles_rv_bare_relative_dir }}/config"
      mode: "0600"

- name: Dotfiles | Ensure config alias is set in ~/.bashrc and ~/.zshrc
  ansible.builtin.lineinfile:
      path: "{{ item }}"
      line: 'alias dotfiles=''git --git-dir="$HOME/{{ dotfiles_rv_bare_relative_dir }}" --work-tree=$HOME'''
      create: true
      mode: "0700"
  loop:
      - "{{ dotfiles_rv_user_home_dir }}/.bashrc"
      - "{{ dotfiles_rv_user_home_dir }}/.zshrc"
      - "{{ dotfiles_rv_user_home_dir }}/.aliasrc"
