---
- name: Bitwarden Desktop | Prerequisites
  ansible.builtin.import_tasks: prerequisites.yml

- name: Bitwarden Desktop | Create install directory
  ansible.builtin.file:
      path: "{{ bitwarden_desktop_rv_install_path }}"
      state: directory
      mode: "0700"

- name: Bitwarden Desktop | Get Version
  ansible.builtin.set_fact:
      bitwarden_desktop_version_details: "{{ lookup('arpanrec.nebula.version_db', 'bitwarden_desktop',
          bitwarden_desktop_rv_version=bitwarden_desktop_rv_version) | from_json }}"

- name: Bitwarden Desktop | Get archive info
  ansible.builtin.stat:
      path: "{{ bitwarden_desktop_rv_install_path }}/{{
          bitwarden_desktop_version_details.download_link | basename }}"
  register: pv_ua_bw_archive_stat

- name: Bitwarden Desktop | Download AppImage
  when: not pv_ua_bw_archive_stat.stat.exists
  ansible.builtin.get_url:
      url: "{{ bitwarden_desktop_version_details.download_link }}"
      dest: "{{ bitwarden_desktop_rv_install_path }}/{{ bitwarden_desktop_version_details.download_link | basename }}"
      checksum: "{{ bitwarden_desktop_version_details.checksum | default(omit) }}"
      mode: "0700"

- name: Bitwarden Desktop | Create desktop icon directory
  ansible.builtin.file:
      path: "{{ bitwarden_desktop_rv_xdg_icon_path | dirname }}"
      state: directory
      mode: "0700"

- name: Bitwarden Desktop | Create desktop icon
  ansible.builtin.template:
      src: templates/bitwarden-desktop-userapps.desktop.j2
      dest: "{{ bitwarden_desktop_rv_xdg_icon_path }}"
      mode: "0600"
