---
dependency:
    name: galaxy
    enabled: true
    options:
        ignore-certs: false
        ignore-errors: false
        role-file: requirements.yml
        requirements-file: requirements.yml
driver:
    name: docker
platforms:
    - name: debian_role_vault_docker
      hostname: debian_role_vault_docker
      image: docker.io/library/debian:bookworm
      dockerfile: Dockerfile.j2
      pre_build_image: false
provisioner:
    name: ansible
    vvv: false
    env:
        ANSIBLE_VERBOSITY: 1
    playbooks:
        converge: converge.yml
        verify: verify.yml
    inventory:
        group_vars:
            all:
                ansible_python_interpreter: /usr/bin/python3
scenario:
    name: role.vault.docker
    converge_sequence:
        - converge
    destroy_sequence:
        - destroy
    create_sequence:
        - dependency
        - create
    test_sequence:
        - syntax
        - destroy
        - dependency
        - create
        - converge
        - verify
        - idempotence
        - destroy
verifier:
    name: ansible
