---
- name: Vault | Molecule | Verify
  hosts: all
  gather_facts: false
  tasks:
      - name: Vault | Molecule | Verify | Import Roles for variables
        ansible.builtin.import_role:
            name: arpanrec.nebula.vault
            tasks_from: prerequisites

      - name: Vault | Molecule | Verify | Get Version Details
        ansible.builtin.set_fact:
            vault_tmp_version_details: "{{ lookup('arpanrec.nebula.version_db', 'vault',
                vault_rv_version=vault_rv_version) | from_json }}"

      - name: Vault | Molecule | Verify | Get vault version from shell
        ansible.builtin.command: vault --version
        environment:
            PATH: "{{ vault_rv_install_path }}:{{ ansible_env.PATH }}"
        register: vault_rv_version_shell_result
        changed_when: false

      - name: Vault | Molecule | Verify | Fail if vault version is not present
        ansible.builtin.assert:
            that: vault_rv_version_shell_result.stdout_lines[0]
                is match('Vault v' + vault_tmp_version_details.version + '.*')
            success_msg: Vault Version {{ vault_tmp_version_details.version }} is installed
            fail_msg: Vault Version {{ vault_tmp_version_details.version }} is not installed,
                Shell result {{ vault_rv_version_shell_result.stdout }}
