---
dependency:
    name: galaxy
    enabled: true
    options:
        ignore-certs: false
        ignore-errors: false
        role-file: requirements.yml
        requirements-file: requirements.yml
driver:
    name: docker
platforms:
    - name: plugins_lookup_version_db_default
      image: debian
      hostname: plugins_lookup_version_db_default
      dockerfile: Dockerfile.j2
      pre_build_image: false
provisioner:
    name: ansible
    playbooks:
        verify: verify.yml
    env:
        ANSIBLE_VERBOSITY: 5
scenario:
    name: plugins.lookup.version_db.default
    converge_sequence:
        - converge
    destroy_sequence:
        - destroy
    create_sequence:
        - dependency
        - create
    test_sequence:
        - syntax
        - destroy
        - dependency
        - create
        - converge
        - verify
        - idempotence
        - destroy
verifier:
    name: ansible
