---
- name: Golang | Molecule | Verify
  hosts: all
  gather_facts: true
  tasks:
      - name: Golang | Molecule | Verify | Debug
        ansible.builtin.debug:
            msg: "{{ lookup('arpanrec.nebula.version_db', 'bws', app_name11='app_name_231532562375237') }}"
