---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian
    image: docker.io/library/debian:bullseye
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
  inventory:
    host_vars:
      debian:
        user_add_rv_username: test
verifier:
  name: ansible
scenario:
  name: role.user_add.default
  test_sequence:
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
