---
- name: Linux Patching | Install Packages | Checking Prerequisite | Include Common Checks
  ansible.builtin.import_tasks: prerequisite.yml

- name: Linux Patching | Install Packages | Purge to resolve conflicts
  ansible.builtin.apt:
    name: ntp
    state: absent
    purge: true

- name: Linux Patching | Install Packages | Upgrade existing all packages in Debian
  ansible.builtin.apt:
    update_cache: true
  when: linux_patching_rv_upgrade_existing_packages
  register: linux_patching_rv_upgrade_result

- name: Linux Patching | Install Packages | Reboot After Packages Upgrade
  when: linux_patching_rv_upgrade_result.changed and linux_patching_rv_init_system_systemd
  ansible.builtin.import_tasks:
    file: reboot.yml

- name: Linux Patching | Install Packages | Install specific essential packages in Debian
  ansible.builtin.apt:
    name: "{{ linux_patching_rv_packages | default([]) + linux_patching_rv_extra_packages | default([]) + linux_patching_rv_managed_packages | default([]) }}"
    state: present
    update_cache: true
  register: linux_patching_rv_extra_install

- name: Linux Patching | Install Packages | Reboot After Packages Install
  when: linux_patching_rv_extra_install.changed and linux_patching_rv_init_system_systemd
  ansible.builtin.import_tasks:
    file: reboot.yml

- name: Linux Patching | Install Packages | Install headers linux-headers-{{ ansible_kernel }}
  ansible.builtin.apt:
    name: "linux-headers-{{ ansible_kernel }}"
    state: present
    update_cache: true
  when: linux_patching_rv_install_headers
  ignore_errors: true
  register: linux_patching_rv_install_headers_tmp_kernel_version_installed

- name: Linux Patching | Install Packages | Install generic headers linux-headers
  ansible.builtin.apt:
    name: "linux-headers"
    state: present
    update_cache: true
  when: linux_patching_rv_install_headers and linux_patching_rv_install_headers_tmp_kernel_version_installed.failed
  register: linux_patching_rv_install_generic_headers_tmp_kernel_version_installed

- name: Linux Patching | Install Packages | Reboot after kernel install
  ansible.builtin.import_tasks:
    file: reboot.yml
  when: >
    linux_patching_rv_init_system_systemd
    and
    (
      linux_patching_rv_install_generic_headers_tmp_kernel_version_installed.changed
      or
      linux_patching_rv_install_headers_tmp_kernel_version_installed.changed
    )
