---
- name: Linux Patching | Prerequisite | Gather Facts
  ansible.builtin.setup:

- name: Linux Patching | Prerequisite | Checking Platform Compatibility
  ansible.builtin.fail:
      msg: "{{ ansible_facts.distribution }} is not supported by this role"
  when: ansible_facts.distribution not in ['Debian']

- name: Linux Patching | Prerequisite | Get System 1 PID Details
  ansible.builtin.command: ps -p 1
  register: linux_patching_rv_tmp_one_pid_shell_result
  changed_when: false

- name: Linux Patching | Prerequisite | Assume System Is Not In Systemd
  ansible.builtin.set_fact:
      linux_patching_rv_init_system_systemd: "{{ linux_patching_rv_tmp_one_pid_shell_result.stdout_lines[1] \
          | split(' ') | last == 'systemd' }}"
