---
- name: Application User | Checking user_add_rv_username is defined
  ansible.builtin.assert:
      that:
          - user_add_rv_username is defined
          - user_add_rv_username != None
      success_msg: "user_add_rv_username is defined."
      fail_msg: "user_add_rv_username is not defined. Username is required to create a user."

- name: Application User | Checking is user_add_rv_user_nopasswd_commands is a type of list
  ansible.builtin.assert:
      that:
          - user_add_rv_user_nopasswd_commands | type_debug == 'list'
      success_msg: "user_add_rv_user_nopasswd_commands is a list."
      fail_msg: "user_add_rv_user_nopasswd_commands is not a list.
          user_add_rv_user_nopasswd_commands should be a list."

- name: Application User | Checking is user_add_rv_ssh_access_public_key_content_list is a type of list
  ansible.builtin.assert:
      that:
          - user_add_rv_ssh_access_public_key_content_list | type_debug == 'list'
      success_msg: "user_add_rv_ssh_access_public_key_content_list is a list."
      fail_msg: "user_add_rv_ssh_access_public_key_content_list is not a list.
          user_add_rv_ssh_access_public_key_content_list should be a list."

- name: Application User | Checking is user_add_rv_user_extra_groups is a type of list
  ansible.builtin.assert:
      that:
          - user_add_rv_user_extra_groups | type_debug == 'list'
      success_msg: "user_add_rv_user_extra_groups is a list."
      fail_msg: "user_add_rv_user_extra_groups is not a list.
          user_add_rv_user_extra_groups should be a list."

- name: Application User | Setting Group Name
  ansible.builtin.set_fact:
      user_add_rv_user_primary_group: "{{ user_add_rv_username }}"
  when: >
      user_add_rv_user_primary_group is not defined
      or
      user_add_rv_user_primary_group | length < 1
