---
- name: Application User | Adding User | Adding The Group
  ansible.builtin.group:
      name: "{{ user_add_rv_user_primary_group | ansible.builtin.default(user_add_rv_username, true) }}"
      gid: "{{ user_add_rv_user_primary_gid | ansible.builtin.default(omit) }}"
      system: "{{ user_add_rv_is_system_user }}"
      state: present

- name: Application User | Adding User | Generate Password Hash
  ansible.builtin.set_fact:
      __user_add_rv_password_hash_tmp: "{{ user_add_rv_password | community.general.password_hash('sha512') }}"
  when: user_add_rv_password is defined and user_add_rv_password | ansible.builtin.length > 0

- name: Application User | Adding User | Adding The User
  ansible.builtin.user:
      name: "{{ user_add_rv_username }}"
      shell: "{{ user_add_rv_user_default_shell }}"
      system: "{{ user_add_rv_is_system_user }}"
      state: present
      groups: "{{ (user_add_rv_user_extra_groups | ansible.builtin.length > 0)
          | ansible.builtin.ternary(user_add_rv_user_extra_groups, omit) }}"
      append: "{{ (user_add_rv_user_extra_groups | ansible.builtin.length > 0) | ansible.builtin.ternary(true, omit) }}"
      uid: "{{ user_add_rv_uid | ansible.builtin.default(omit) }}"
      group: "{{ user_add_rv_user_primary_group | ansible.builtin.default(user_add_rv_username, true) }}"
      create_home: true
      home: "{{ user_add_rv_user_home_dir | ansible.builtin.default(omit, True) }}"
      expires: -1
      password: "{{ __user_add_rv_password_hash_tmp | ansible.builtin.default(omit) }}"
      update_password: "{{ (__user_add_rv_password_hash_tmp is defined
          and __user_add_rv_password_hash_tmp | ansible.builtin.length > 0)
          | ansible.builtin.ternary('always', omit) }}"

- name: Application User | Adding User | Deploying SSH Key
  ansible.posix.authorized_key:
      user: "{{ user_add_rv_username }}"
      key: "{{ item }}"
      state: present
      comment: added by ansible automation
  with_items: "{{ user_add_rv_ssh_access_public_key_content_list }}"
  when: user_add_rv_ssh_access_public_key_content_list | ansible.builtin.length > 0

- name: Application User | Adding User | Adding User To The Sudoers
  when: user_add_rv_user_nopasswd_commands | ansible.builtin.length > 0
  ansible.builtin.lineinfile:
      path: "{{ __user_add_sudoers_file }}"
      line: "{{ user_add_rv_username }} ALL=(ALL) NOPASSWD: {{ item }}"
      create: true
      validate: /usr/sbin/visudo -cf %s
      mode: "0440"
  with_items:
      - "{{ user_add_rv_user_nopasswd_commands }}"
