---
- name: "Application User | Removing User | Remove The User"
  ansible.builtin.user:
      name: "{{ user_add_rv_username }}"
      state: absent
      remove: true

- name: "Application User | Removing User | Remove The Default Group"
  ansible.builtin.group:
      name: "{{ user_add_rv_username }}"
      state: absent

- name: "Application User | Removing User | Remove Sudoers File"
  ansible.builtin.file:
      path: "{{ user_add_rv_sudoers_file }}"
      state: absent
