---
- name: Hadolint | Prerequisites | Fail If Root User
  ansible.builtin.command: whoami
  register: __rl_sw_current_shelluser_shell_result
  failed_when: __rl_sw_current_shelluser_shell_result.stdout == "root"
  changed_when: false

- name: Hadolint | Prerequisites | Gather Facts
  ansible.builtin.setup:
