---
- name: Gitea | Restart systemd service
  ansible.builtin.systemd_service:
      name: "{{ __gitea_systemd_service_name }}"
      state: restarted
      enabled: true
      daemon_reload: true
      masked: false
  when: __gitea_rv_init_system_systemd | ansible.builtin.default(default_value=true)

- name: Fail2ban | Restart service
  when: "'fail2ban' in ansible_facts.packages and ansible_facts.packages['fail2ban'] | ansible.builtin.length > 0"
  ansible.builtin.systemd_service:
      name: fail2ban
      state: restarted
      enabled: true
      daemon_reload: true
      masked: false
