---
dependency:
    name: galaxy
    enabled: true
    options:
        ignore-certs: false
        ignore-errors: false
        role-file: requirements.yml
        requirements-file: requirements.yml
driver:
    name: docker
platforms:
    - name: debian_role_get_certificate_ownca_docker
      dockerfile: Dockerfile.j2
      hostname: debian_role_get_certificate_ownca_docker
      image: "docker.io/library/debian:bookworm"
      pre_build_image: false
      privileged: false
provisioner:
    name: ansible
    playbooks:
        converge: converge.yml
        prepare: prepare.yml
    vvv: false
    env:
        ANSIBLE_VERBOSITY: 1
    inventory:
        group_vars:
            all:
                ansible_python_interpreter: /usr/bin/python3
                get_certificate_ownca_rv_private_key_path: /tmp/ownca_private_key.pem
                get_certificate_ownca_rv_certificate_path: /tmp/ownca_certificate_path.pem
                get_certificate_ownca_rv_private_key_password: password
                get_certificate_ownca_rv_getcert_private_key_password: password
                get_certificate_ownca_rv_getcert_private_key_path: /tmp/private_key.pem
                get_certificate_ownca_rv_getcert_certificate_path: /tmp/certificate_path.pem
                get_certificate_ownca_rv_getcert_molecule_prepare_csr_path: /tmp/ownca_csr.pem
                get_certificate_ownca_rv_getcert_certificatefullchain_path: /tmp/certificate_chain_path.pem
                get_certificate_ownca_rv_getcert_key_usage:
                    - digitalSignature
                    - nonRepudiation
                    - keyEncipherment
                    - dataEncipherment
                    - keyCertSign
                    - cRLSign
                get_certificate_ownca_rv_getcert_extended_key_usage:
                    - serverAuth
                    - clientAuth
                    - codeSigning
                    - emailProtection
                    - timeStamping
                    - OCSPSigning
                    - msCTLSign
                get_certificate_ownca_rv_getcert_subject_alt_name:
                    - "DNS:www.arpanrec.com"
                    - "IP:172.0.0.1"
                get_certificate_ownca_rv_getcert_subject:
                    commonName: www.arpanrec.com
                get_certificate_ownca_rv_getcert_basic_constraints:
                    - "CA:TRUE"
                    - "pathlen:0"
                get_certificate_ownca_rv_getcert_private_key_file_mode: "0600"
scenario:
    name: role.get_certificate_ownca.docker
    converge_sequence:
        - converge
    destroy_sequence:
        - destroy
    create_sequence:
        - dependency
        - create
        - prepare
    test_sequence:
        - syntax
        - destroy
        - dependency
        - create
        - prepare
        - converge
        - idempotence
        - destroy
verifier:
    name: ansible
log: true
role_name_check: 0
