---
- name: Bitwarden CLI | Prerequisites
  ansible.builtin.import_tasks: prerequisites.yml

- name: Bitwarden CLI | BWS SDK | Get Dynamic Version
  when: bws_sdk_version_tag is not defined
  block:
      - name: Bitwarden CLI | BWS SDK | Get Latest Release from github
        ansible.builtin.uri:
            url: "https://api.github.com/repos/bitwarden/sdk/releases/latest"
            return_content: true
            headers:
                Accept: "application/vnd.github.v3+json"
        register: bws_sdk_version_for_github

      - name: Bitwarden CLI | BWS SDK | Set Dynamic Version
        ansible.builtin.set_fact:
            bws_sdk_version_tag: "{{ bws_sdk_version_for_github.json.tag_name[5:] }}"

- name: Bitwarden CLI | BWS SDK | Get downloaded file stat
  ansible.builtin.stat:
      path: "{{ bws_sdk_tmp_zip_download_path }}"
  register: bws_sdk_tmp_zip_file_stat

- name: Bitwarden CLI | BWS SDK | New Install
  when: not bws_sdk_tmp_zip_file_stat.stat.exists
  block:
      - name: Bitwarden CLI | BWS SDK | New Install | Download
        ansible.builtin.get_url:
            url: "{{ bws_sdk_download_url }}"
            dest: "{{ bws_sdk_tmp_zip_download_path }}"
            mode: "0700"

      - name: Bitwarden CLI | BWS SDK | New Install | Remove old directory
        ansible.builtin.file:
            path: "{{ item }}"
            state: absent
        with_items:
            - "{{ bws_sdk_bin_dir }}/bws"
            - "{{ bws_sdk_tmp_dir }}/bws"

- name: Bitwarden CLI | BWS SDK | New Install | Extract
  ansible.builtin.unarchive:
      src: "{{ bws_sdk_tmp_zip_download_path }}"
      dest: "{{ bws_sdk_tmp_dir }}"
      remote_src: true

- name: Bitwarden CLI | BWS SDK | New Install | bws_sdk_bin_dir | Create
  ansible.builtin.file:
      path: "{{ bws_sdk_bin_dir }}"
      state: directory
      mode: "0700"

- name: Bitwarden CLI | BWS SDK | New Install | Copy
  ansible.builtin.copy:
      src: "{{ bws_sdk_tmp_dir }}/bws"
      dest: "{{ bws_sdk_bin_dir }}/bws"
      mode: "0700"
      remote_src: true
