---
code_rv_tmp_dir: "{{ ansible_facts.user_dir }}/.tmp/code"
code_rv_bin_dir: "{{ ansible_facts.user_dir }}/.local/bin"
code_rv_install_path: "{{ ansible_facts.user_dir }}/.local/share/vscode"
code_rv_xdg_icon_dir: "{{ ansible_facts.user_dir }}/.local/share/applications"
code_rv_ext_to_be_installed:
    - "angular.ng-template"
    - "bradlc.vscode-tailwindcss"
    - "davidanson.vscode-markdownlint"
    - "dbaeumer.vscode-eslint"
    - "dhruv.maven-dependency-explorer"
    - "dsznajder.es7-react-js-snippets"
    - "esbenp.prettier-vscode"
    - "exiasr.hadolint"
    - "foxundermoon.shell-format"
    - "github.codespaces"
    - "github.copilot"
    - "github.copilot-chat"
    - "github.github-vscode-theme"
    - "github.remotehub"
    - "github.vscode-codeql"
    - "github.vscode-github-actions"
    - "github.vscode-pull-request-github"
    - "gitlab.gitlab-workflow"
    - "golang.go"
    - "hashicorp.terraform"
    - "johnpapa.angular2"
    - "ms-azuretools.vscode-docker"
    - "ms-python.black-formatter"
    - "ms-python.debugpy"
    - "ms-python.isort"
    - "ms-python.mypy-type-checker"
    - "ms-python.pylint"
    - "ms-python.python"
    - "ms-python.vscode-pylance"
    - "ms-toolsai.jupyter"
    - "ms-toolsai.jupyter-keymap"
    - "ms-toolsai.jupyter-renderers"
    - "ms-toolsai.vscode-jupyter-cell-tags"
    - "ms-toolsai.vscode-jupyter-slideshow"
    - "ms-vscode-remote.remote-containers"
    - "ms-vscode-remote.remote-ssh"
    - "ms-vscode-remote.remote-ssh-edit"
    - "ms-vscode-remote.remote-wsl"
    - "ms-vscode-remote.vscode-remote-extensionpack"
    - "ms-vscode.azure-repos"
    - "ms-vscode.remote-explorer"
    - "ms-vscode.remote-repositories"
    - "ms-vscode.remote-server"
    - "ms-vscode.vscode-speech"
    - "msjsdiag.vscode-react-native"
    - "pkief.material-icon-theme"
    - "redhat.ansible"
    - "redhat.fabric8-analytics"
    - "redhat.vscode-xml"
    - "redhat.vscode-yaml"
    - "rust-lang.rust-analyzer"
    - "shengchen.vscode-checkstyle"
    - "streetsidesoftware.code-spell-checker"
    - "sumneko.lua"
    - "timonwong.shellcheck"
    - "visualstudioexptteam.intellicode-api-usage-examples"
    - "visualstudioexptteam.vscodeintellicode"
    - "visualstudioexptteam.vscodeintellicode-completions"
    - "wholroyd.jinja"
    - "yzhang.markdown-all-in-one"
