---
- name: Pulumi | Molecule | Converge
  hosts: all
  gather_facts: false
  any_errors_fatal: true
  become: false
  tasks:
      - name: Pulumi | Molecule | Converge | Include Pulumi role
        ansible.builtin.import_role:
            name: arpanrec.nebula.pulumi
