---
ssh_hardening_rv_ssh_port: 22
# Install the packages in all the distributions

# To disable tunneled clear text passwords
# Type: `boolean`
ssh_hardening_rv_ssh_security_password_authentication: false

# Specifies whether root can log in using ssh
# Type: `boolean`
ssh_hardening_rv_ssh_security_permit_root_login: false

# When password authentication is allowed,
# it specifies whether the server allows login to accounts with empty password strings
# Type: `boolean`
ssh_hardening_rv_ssh_security_permit_empty_passwords: false

# Specifies the maximum number of authentication attempts permitted per connection.
#   Once the number of failures reaches half this value, additional failures are logged.
# Type: `int`
ssh_hardening_rv_ssh_security_max_auth_tries: 3

# Specifies whether X11 forwarding is permitted
# Type: `boolean`
ssh_hardening_rv_ssh_security_x11_forwarding: false

# Sets a timeout interval in seconds after which if no data has been received from the client
# Type: `int`
ssh_hardening_rv_ssh_security_client_alive_interval: 60

# Sets the number of client alive messages which may be sent without sshd(8) \
#   receiving any messages back from the client. If this threshold is reached \
#   while client alive messages are being sent, sshd will disconnect the client, terminating the session
# Type: `int`
ssh_hardening_rv_ssh_security_client_alive_count_max: 3

# Restart sshd handlers

ssh_hardening_rv_ssh_security_challenge_response_authentication: false

# defaults file for fail2ban

ssh_hardening_rv_fail2ban_loglevel: INFO
ssh_hardening_rv_fail2ban_logtarget: /var/log/fail2ban.log

ssh_hardening_rv_fail2ban_ignoreself: "true"
ssh_hardening_rv_fail2ban_ignoreips:
    - "127.0.0.1/8 ::1"

# In seconds
ssh_hardening_rv_fail2ban_bantime: 600
ssh_hardening_rv_fail2ban_findtime: 600

ssh_hardening_rv_fail2ban_maxretry: 5
ssh_hardening_rv_fail2ban_destemail: root@{{ ansible_fqdn }}
ssh_hardening_rv_fail2ban_sender: root@{{ ansible_fqdn }}

ssh_hardening_rv_fail2ban_configuration: []
#  - option: loglevel
#    value: "INFO"
#    section: Definition

ssh_hardening_rv_fail2ban_jail_configuration: []
#  - option: ignoreself
#    value: "true"
#    section: DEFAULT

# Path to directory containing filters to copy in filter.d
# ssh_hardening_rv_fail2ban_filterd_path:
