---
dependency:
    name: galaxy
    enabled: true
    options:
        ignore-certs: false
        ignore-errors: false
        role-file: requirements.yml
        requirements-file: requirements.yml
driver:
    name: docker
platforms:
    - name: debian_role_code_docker
      image: docker.io/library/debian:bookworm
      hostname: debian_role_code_docker
      privileged: false
      dockerfile: Dockerfile.j2
      pre_build_image: false
provisioner:
    name: ansible
    vvv: false
    env:
        ANSIBLE_VERBOSITY: 1
    playbooks:
        converge: converge.yml
        verify: verify.yml
    inventory:
        group_vars:
            all:
                code_rv_ext_to_be_installed:
                    - "akamud.vscode-theme-onedark"
scenario:
    name: role.code.docker
    converge_sequence:
        - dependency
        - converge
    destroy_sequence:
        - destroy
    create_sequence:
        - dependency
        - create
    test_sequence:
        - syntax
        - destroy
        - dependency
        - create
        - converge
        - verify
        - idempotence
        - destroy
verifier:
    name: ansible
