---
- name: Visual Studio Code | Molecule | Verify
  hosts: all
  gather_facts: false
  become: false
  tasks:
      - name: Visual Studio Code | Molecule | Verify | Import Roles for variables
        ansible.builtin.import_role:
            name: arpanrec.nebula.code
            tasks_from: prerequisites

      - name: Visual Studio Code | Molecule | Verify | Set Fact for code bin environment
        ansible.builtin.set_fact:
            code_rv_tmp_bin_env:
                DONT_PROMPT_WSL_INSTALL: true
                PATH: "{{ code_rv_bin_dir }}:{{ ansible_env.PATH }}"

      - name: Visual Studio Code | Molecule | Verify | Get code version from shell
        ansible.builtin.command: code --version
        environment: "{{ code_rv_tmp_bin_env }}"
        register: code_rv_tmp_version_shell_result
        changed_when: false

      - name: Visual Studio Code | Molecule | Verify | Set Fact for code version
        ansible.builtin.set_fact:
            code_version_details: "{{ lookup('arpanrec.nebula.version_db', 'code',
                code_rv_version=code_rv_version) }}"

      - name: Visual Studio Code | Molecule | Verify | Fail if code version is not present
        ansible.builtin.assert:
            that: code_rv_tmp_version_shell_result.stdout_lines[0] is match(code_version_details.version + ".*")
            success_msg: Visual Studio Code {{ code_version_details.version }} is installed
            fail_msg: "Visual Studio Code {{ code_version_details.version }} is not installed, \
                Shell result {{ code_rv_tmp_version_shell_result.stdout }}"
