---
__uv_rv_tarball_download_path: "{{ uv_rv_tmp_download_dir }}\
    /uv-{{ __uv_version_details.version }}.tar.gz"
__uv_rv_tmp_unarchive_dir: "{{ uv_rv_tmp_download_dir }}-{{ __uv_version_details.version }}"
