---
- name: Gitea | Gather root facts.
  ansible.builtin.setup:

- name: Gitea | Get Release.
  ansible.builtin.set_fact:
      gitea_version_details: "{{ lookup('arpanrec.nebula.version_db', 'gitea',
          gitea_rv_version=gitea_rv_version) | from_json }}"

- name: Gitea | Prerequisite | Get system 1 PID Details.
  ansible.builtin.command: ps -p 1
  register: gitea_rv_tmp_one_pid_shell_result
  changed_when: false

- name: Gitea | Prerequisite | Assume system is not in systemd.
  ansible.builtin.set_fact:
      gitea_rv_init_system_systemd: "{{ gitea_rv_tmp_one_pid_shell_result.stdout_lines[1] \
          | split(' ') | last == 'systemd' }}"

- name: Gitea | Install dependencies.
  ansible.builtin.apt:
      name:
          - git
          - git-lfs
          - python3-requests

- name: Gitea | Add git group.
  ansible.builtin.group:
      name: "{{ gitea_service_group }}"
      state: present
      system: true
  notify:
      - Gitea | Restart systemd service

- name: Gitea | Add git user.
  ansible.builtin.user:
      name: "{{ gitea_service_user }}"
      group: "{{ gitea_service_group }}"
      shell: /bin/bash
      home: "{{ gitea_service_user_home_directory }}"
      system: true
  notify:
      - Gitea | Restart systemd service

- name: Gitea | Create directories.
  ansible.builtin.file:
      path: "{{ item }}"
      owner: "{{ gitea_service_user }}"
      group: "{{ gitea_service_group }}"
      mode: "0755"
      state: directory
  loop:
      - "{{ gitea_app_ini_file | dirname }}"
      - "{{ gitea_secret_key_file | dirname }}"
      - "{{ gitea_internal_token_file | dirname }}"
      - "{{ gitea_oauth2_jwt_secret_file | dirname }}"
      - "{{ gitea_lfs_jwt_secret_file | dirname }}"
      - "{{ gitea_working_directory }}"
      - "{{ gitea_app_data_directory }}"
      - "{{ gitea_repository_root_directory }}"
      - "{{ gitea_lfs_directory }}"
      - "{{ gitea_git_home_directory }}"
      - "{{ gitea_custom_directory }}"
      - "{{ gitea_sqlite3_db_file | dirname }}"
      - "{{ gitea_log_root_path }}"
      - "{{ gitea_log_file | dirname }}"
      - "{{ gitea_service_user_home_directory }}/.local/bin"
      - "{{ gitea_service_user_home_directory }}/.config/systemd/user"
  notify:
      - Gitea | Restart systemd service

- name: Gitea | Get architecture.
  ansible.builtin.command:
      argv:
          - dpkg
          - --print-architecture
  register: gitea_print_architecture
  changed_when: false

- name: Gitea | Write gpg key.
  ansible.builtin.copy:
      dest: "{{ gitea_service_user_home_directory }}/teabot-gpg.asc"
      content: "{{ gitea_teabot_gpg_key }}"
      owner: "{{ gitea_service_user }}"
      group: "{{ gitea_service_group }}"
      mode: "0644"

- name: Gitea | Import gpg key.
  ansible.builtin.command:
      argv:
          - gpg
          - --import
          - "{{ gitea_service_user_home_directory }}/teabot-gpg.asc"
  register: gitea_import_gpg_key_res
  changed_when: "'imported' in gitea_import_gpg_key_res.stdout"

- name: Gitea | Download gpg signature.
  ansible.builtin.get_url:
      url: "{{ gitea_version_details.download_link }}.asc"
      mode: "0755"
      owner: "{{ gitea_service_user }}"
      group: "{{ gitea_service_group }}"
      dest: "{{ gitea_service_user_home_directory }}/gitea-{{ gitea_version_details.version }}.asc"

- name: Gitea | Download binary.
  ansible.builtin.get_url:
      url: "{{ gitea_version_details.download_link }}"
      checksum: "{{ gitea_version_details.checksum | default(omit) }}"
      mode: "0755"
      owner: root
      group: root
      dest: "{{ gitea_executable }}"
  notify:
      - Gitea | Restart systemd service

- name: Gitea | Verify gpg signature.
  ansible.builtin.command:
      argv:
          - gpg
          - --verify
          - "{{ gitea_service_user_home_directory }}/gitea-{{ gitea_version_details.version }}.asc"
          - "{{ gitea_executable }}"
  register: gitea_verify_gpg_signature_res
  failed_when: gitea_verify_gpg_signature_res.rc != 0
  changed_when: false

- name: Gitea | Create systemd service.
  ansible.builtin.template:
      src: service.j2
      dest: /etc/systemd/system/{{ gitea_systemd_service_name }}
      owner: root
      group: root
      mode: "0644"
      backup: false
  notify:
      - Gitea | Restart systemd service

- name: Gitea | Secrets.
  ansible.builtin.import_tasks:
      file: secrets.yml

- name: Gitea | Gitea ini config.
  community.general.ini_file:
      path: "{{ gitea_app_ini_file }}"
      owner: "{{ gitea_service_user }}"
      group: "{{ gitea_service_group }}"
      mode: "0640"
      create: true
      backup: false
      no_extra_spaces: false
      section: "{{ item.section | default(omit) }}"
      option: "{{ item.option }}"
      value: "{{ item.value }}"
  loop: "{{ gitea_default_config }}"
  notify:
      - Gitea | Restart systemd service

- name: Gitea | Postgresql.
  when: gitea_config_db_postgresql is defined
      and gitea_config_db_postgresql is not none
      and gitea_config_db_postgresql | length > 1
  ansible.builtin.import_tasks:
      file: db-postgresql.yml

- name: Gitea | sqlite3 DB Config.
  when: gitea_config_db_postgresql is not defined
      or gitea_config_db_postgresql is none
      or gitea_config_db_postgresql | length == 0
  community.general.ini_file:
      path: "{{ gitea_app_ini_file }}"
      owner: "{{ gitea_service_user }}"
      group: "{{ gitea_service_group }}"
      mode: "0640"
      create: false
      backup: false
      no_extra_spaces: false
      section: "{{ item.section | default(omit) }}"
      option: "{{ item.option }}"
      value: "{{ item.value }}"
  loop:
      - { section: database, option: DB_TYPE, value: sqlite3 }
      - { section: database, option: PATH, value: "{{ gitea_sqlite3_db_file }}" }
  notify:
      - Gitea | Restart systemd service

- name: Gitea | SSL | Create directories.
  when: gitea_protocol == 'https'
  block:
      - name: Gitea | SSL | Create directories
        ansible.builtin.file:
            path: "{{ item }}"
            owner: "{{ gitea_service_user }}"
            group: "{{ gitea_service_group }}"
            mode: "0755"
            state: directory
        loop:
            - "{{ gitea_http_key_pem_file | dirname }}"
            - "{{ gitea_http_cert_pem_file | dirname }}"
        notify:
            - Gitea | Restart systemd service

      - name: Gitea | SSL | Write Certificates.
        ansible.builtin.copy:
            dest: "{{ item.dest }}"
            content: "{{ item.content }}"
            owner: "{{ gitea_service_user }}"
            group: "{{ gitea_service_group }}"
            mode: "{{ item.mode }}"
        loop:
            - dest: "{{ gitea_http_key_pem_file }}"
              content: "{{ gitea_http_key_pem_content }}"
              mode: "0640"
            - dest: "{{ gitea_http_cert_pem_file }}"
              content: "{{ gitea_http_cert_pem_content }}"
              mode: "0644"
        notify:
            - Gitea | Restart systemd service

      - name: Gitea | SSL | Git ea ini file.
        community.general.ini_file:
            path: "{{ gitea_app_ini_file }}"
            owner: "{{ gitea_service_user }}"
            group: "{{ gitea_service_group }}"
            mode: "0640"
            create: false # It should be created by the previous task.
            backup: false
            no_extra_spaces: false
            section: "{{ item.section | default(omit) }}"
            option: "{{ item.option }}"
            value: "{{ item.value }}"
        loop:
            - { section: server, option: CERT_FILE, value: "{{ gitea_http_cert_pem_file }}" }
            - { section: server, option: KEY_FILE, value: "{{ gitea_http_key_pem_file }}" }
        notify:
            - Gitea | Restart systemd service

- name: Gitea | Gitea extra configs.
  community.general.ini_file:
      path: "{{ gitea_app_ini_file }}"
      owner: "{{ gitea_service_user }}"
      group: "{{ gitea_service_group }}"
      mode: "0640"
      create: false # It should be created by the previous task.
      backup: false
      no_extra_spaces: false
      section: "{{ item.section | default(omit) }}"
      option: "{{ item.option }}"
      value: "{{ item.value }}"
  loop: "{{ gitea_extra_config }}"
  notify:
      - Gitea | Restart systemd service

- name: Gitea | Flush handlers.
  ansible.builtin.meta: flush_handlers

- name: Gitea | Enable systemd service.
  ansible.builtin.systemd_service:
      name: "{{ gitea_systemd_service_name }}"
      state: started
      enabled: true
      daemon_reload: true
      masked: false
  register: gitea_systemd_enable_res
  failed_when: gitea_rv_init_system_systemd
      and gitea_systemd_enable_res.failed

- name: Gitea | Gather the package facts.
  ansible.builtin.package_facts:
      manager: auto

- name: Gitea | Allow ufw port.
  when: "'ufw' in ansible_facts.packages and ansible_facts.packages['ufw'] | length > 0"
  community.general.ufw:
      state: enabled
      port: "{{ item }}"
      comment: Gitea managed by ansible easyiac init stack.
      proto: tcp
      rule: allow
      to: 0.0.0.0/0
  loop:
      - "{{ gitea_ssh_port }}"
      - "{{ gitea_http_port }}"

- name: Gitea | Fail2ban.
  when: "'fail2ban' in ansible_facts.packages and ansible_facts.packages['fail2ban'] | length > 0"
  ansible.builtin.import_tasks:
      file: fail2ban.yml

- name: Gitea | Post Install.
  ansible.builtin.import_tasks:
      file: post-install.yml
  environment:
      PGSSLROOTCERT: "{{ gitea_config_db_pg_ssl_root_cert_file }}"
      PGSSLCERT: "{{ gitea_config_db_pg_ssl_cert_file }}"
      PGSSLKEY: "{{ gitea_config_db_pg_ssl_key_file }}"
      GITEA_CUSTOM: "{{ gitea_custom_directory }}"
      GITEA_WORK_DIR: "{{ gitea_working_directory }}"

- name: Gitea | Global runner token.
  when: gitea_global_runner_registration_token_file_path is defined
      and gitea_global_runner_registration_token_file_path is not none
      and gitea_global_runner_registration_token_file_path | length > 1
  ansible.builtin.import_tasks:
      file: global-runner-token.yml

- name: Gitea | Admin token.
  when: gitea_admin_token_file_path is defined
      and gitea_admin_token_file_path is not none
      and gitea_admin_token_file_path | length > 1
      and gitea_admin_user_username is defined
      and gitea_admin_user_username is not none
      and gitea_admin_user_username | length > 1
  ansible.builtin.import_tasks:
      file: admin-token.yml
