---
- name: Gitea | Prerequisite | Gather Root Facts
  ansible.builtin.setup:

- name: Gitea | Prerequisite | Get System 1 PID Details
  ansible.builtin.command: ps -p 1
  register: __gitea_rv_tmp_one_pid_shell_result
  changed_when: false

- name: Gitea | Prerequisite | Assume System Is Not In Systemd
  ansible.builtin.set_fact:
      __gitea_rv_init_system_systemd: "{{ __gitea_rv_tmp_one_pid_shell_result.stdout_lines[1] \
          | ansible.builtin.split(sep=' ') | ansible.builtin.last == 'systemd' }}"

- name: Gitea | Prerequisite | Packages Are Present
  ansible.builtin.shell: "command -v {{ item }} >/dev/null 2>&1"
  changed_when: false
  with_items:
      - gpg

- name: Gitea | Prerequisite | Write GPG Key
  ansible.builtin.copy:
      dest: "/tmp/teabot-gpg.asc"
      content: "{{ __gitea_teabot_gpg_key }}"
      mode: "0644"

- name: Gitea | Prerequisite | Import GPG Key
  ansible.builtin.command:
      argv:
          - gpg
          - --import
          - "/tmp/teabot-gpg.asc"
  register: __gitea_import_gpg_key_res
  changed_when: "'imported' in __gitea_import_gpg_key_res.stdout"
