---
- name: Gitea | Secrets | Generate Gitea SECRET_KEY If Not Provided
  become: true
  become_user: "{{ gitea_service_user }}"
  ansible.builtin.shell: |+
      {{ __gitea_executable }} generate secret SECRET_KEY > {{ __gitea_secret_key_file }};
      chmod 400 {{ __gitea_secret_key_file }};
  args:
      creates: "{{ __gitea_secret_key_file }}"
      executable: /usr/bin/bash
  when: gitea_secret_key is not ansible.builtin.defined
      or gitea_secret_key | ansible.builtin.string | ansible.builtin.length == 0
  notify:
      - Gitea | Restart systemd service

- name: Gitea | Secrets | Read Gitea SECRET_KEY From File
  ansible.builtin.slurp:
      src: "{{ __gitea_secret_key_file }}"
  register: __gitea_remote_secret_key
  when: gitea_secret_key is not ansible.builtin.defined
      or gitea_secret_key | ansible.builtin.string | ansible.builtin.length == 0

- name: Gitea | Secrets | Set Fact Secret Key
  ansible.builtin.set_fact:
      gitea_secret_key: "{{ __gitea_remote_secret_key['content'] | ansible.builtin.b64decode }}"
  when: gitea_secret_key is not ansible.builtin.defined
      or gitea_secret_key | ansible.builtin.string | ansible.builtin.length == 0

- name: Gitea | Secrets | Generate Gitea INTERNAL_TOKEN If Not Provided
  become: true
  become_user: "{{ gitea_service_user }}"
  ansible.builtin.shell: |+
      {{ __gitea_executable }} generate secret INTERNAL_TOKEN > {{ __gitea_internal_token_file }};
      chmod 400 {{ __gitea_internal_token_file }};
  args:
      creates: "{{ __gitea_internal_token_file }}"
      executable: /usr/bin/bash
  when: gitea_internal_token is not ansible.builtin.defined
      or gitea_internal_token | ansible.builtin.string | ansible.builtin.length == 0
  notify:
      - Gitea | Restart systemd service

- name: Gitea | Secrets | Read Gitea INTERNAL_TOKEN From File
  ansible.builtin.slurp:
      src: "{{ __gitea_internal_token_file }}"
  register: __gitea_remote_internal_token
  when: gitea_internal_token is not ansible.builtin.defined
      or gitea_internal_token | ansible.builtin.string | ansible.builtin.length == 0

- name: Gitea | Secrets | Set Fact Internal Token
  ansible.builtin.set_fact:
      gitea_internal_token: "{{ __gitea_remote_internal_token['content'] | ansible.builtin.b64decode }}"
  when: gitea_internal_token is not ansible.builtin.defined
      or gitea_internal_token | ansible.builtin.string | ansible.builtin.length == 0

- name: Gitea | Secrets | Generate OAuth2 JWT_SECRET If Not Provided
  become: true
  become_user: "{{ gitea_service_user }}"
  ansible.builtin.shell: |+
      {{ __gitea_executable }} generate secret JWT_SECRET > {{ __gitea_oauth2_jwt_secret_file }};
      chmod 400 {{ __gitea_oauth2_jwt_secret_file }};
  args:
      creates: "{{ __gitea_oauth2_jwt_secret_file }}"
      executable: /usr/bin/bash
  when: gitea_oauth2_jwt_secret is not ansible.builtin.defined
      or gitea_oauth2_jwt_secret | ansible.builtin.length == 0
  notify:
      - Gitea | Restart systemd service

- name: Gitea | Secrets | Read OAuth2 JWT_SECRET From File
  ansible.builtin.slurp:
      src: "{{ __gitea_oauth2_jwt_secret_file }}"
  register: __gitea_remote_oauth2_jwt_secret
  when: gitea_oauth2_jwt_secret is not ansible.builtin.defined
      or gitea_oauth2_jwt_secret | ansible.builtin.length == 0

- name: Gitea | Secrets | Set Fact OAuth2 JWT Secret
  ansible.builtin.set_fact:
      gitea_oauth2_jwt_secret: "{{ __gitea_remote_oauth2_jwt_secret['content'] | ansible.builtin.b64decode }}"
  when: gitea_oauth2_jwt_secret is not ansible.builtin.defined
      or gitea_oauth2_jwt_secret | ansible.builtin.length == 0

- name: Gitea | Secrets | Generate LFS JWT_SECRET If Not Provided
  become: true
  become_user: "{{ gitea_service_user }}"
  ansible.builtin.shell: |+
      {{ __gitea_executable }} generate secret JWT_SECRET > {{ __gitea_lfs_jwt_secret_file }};
      chmod 400 {{ __gitea_lfs_jwt_secret_file }};
  args:
      creates: "{{ __gitea_lfs_jwt_secret_file }}"
      executable: /usr/bin/bash
  when: gitea_lfs_jwt_secret is not ansible.builtin.defined
      or gitea_lfs_jwt_secret | ansible.builtin.length == 0
  notify:
      - Gitea | Restart systemd service

- name: Gitea | Secrets | Read LFS JWT_SECRET From File
  ansible.builtin.slurp:
      src: "{{ __gitea_lfs_jwt_secret_file }}"
  register: __gitea_remote_lfs_jwt_secret
  when: gitea_lfs_jwt_secret is not ansible.builtin.defined
      or gitea_lfs_jwt_secret | ansible.builtin.length == 0

- name: Gitea | Secrets | Set Fact LFS JWT Secret
  ansible.builtin.set_fact:
      gitea_lfs_jwt_secret: "{{ __gitea_remote_lfs_jwt_secret['content'] | ansible.builtin.b64decode }}"
  when: gitea_lfs_jwt_secret is not ansible.builtin.defined
      or gitea_lfs_jwt_secret | ansible.builtin.length == 0

- name: Gitea | Secrets | Write The Secrets To File
  ansible.builtin.copy:
      content: "{{ item.content }}"
      dest: "{{ item.dest }}"
      mode: "0400"
      owner: "{{ gitea_service_user }}"
      group: "{{ gitea_service_group }}"
  loop:
      - content: "{{ gitea_secret_key }}"
        dest: "{{ __gitea_secret_key_file }}"
      - content: "{{ gitea_internal_token }}"
        dest: "{{ __gitea_internal_token_file }}"
      - content: "{{ gitea_oauth2_jwt_secret }}"
        dest: "{{ __gitea_oauth2_jwt_secret_file }}"
      - content: "{{ gitea_lfs_jwt_secret }}"
        dest: "{{ __gitea_lfs_jwt_secret_file }}"
