---
- name: Common | Set Secret Vault Endpoint from Environment | Check for ss_secret_vault_endpoint in environment
  when: ss_secret_vault_endpoint is undefined
  block:
    - name: Common | Set Secret Vault Endpoint from Environment | Trying to get vault endpoint from environment variable.
      ansible.builtin.set_fact:
        ss_secret_vault_endpoint_from_env: "{{ lookup('env', 'VAULT_ADDR') }}"

    - name: Common | Set Secret Vault Endpoint from Environment | Setting ss_secret_vault_endpoint from environment variable
      ansible.builtin.set_fact:
        ss_secret_vault_endpoint: "{{ ss_secret_vault_endpoint_from_env }}"
      when:
        - ss_secret_vault_endpoint_from_env is defined
        - ss_secret_vault_endpoint_from_env | length > 1

- name: Common | Set Secret Vault Token from Environment | Check for vault token in environment
  when:
    - ss_secret_vault_endpoint is defined
    - ss_secret_vault_endpoint | length > 1
    - ss_vault_secret_vault_token is undefined
  block:
    - name: Common | Set Secret Vault Token from Environment | Trying to get vault token from environment variable
      ansible.builtin.set_fact:
        ss_vault_secret_vault_token_from_env: "{{ lookup('env', 'VAULT_TOKEN') }}"

    - name: Common | Set Secret Vault Token from Environment | Setting vault token from environment variable
      ansible.builtin.set_fact:
        ss_vault_secret_vault_token: "{{ ss_vault_secret_vault_token_from_env }}"
      when:
        - ss_vault_secret_vault_token_from_env is defined
        - ss_vault_secret_vault_token_from_env | length > 1
