---
dependency:
    name: galaxy
    enabled: true
    options:
        ignore-certs: false
        ignore-errors: false
        role-file: requirements.yml
        requirements-file: requirements.yml
driver:
    name: default
    provider:
        managed: false
        ansible_connection_options:
            ansible_python_interpreter: /usr/bin/python3
            ansible_connection: ssh
platforms:
    - name: rb4-m1
provisioner:
    name: ansible
    vvv: false
    env:
        ANSIBLE_VERBOSITY: 1
    playbooks:
        converge: ../role.linux_patching.docker/converge.yml
    inventory:
        host_vars:
            rb4-m1:
                ansible_host: 192.168.0.219
                ansible_port: 22
                ansible_user: arpan
                ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
                ansible_become_method: sudo
                ansible_become_user: root
scenario:
    name: role.linux_patching.default
    converge_sequence:
        - converge
    test_sequence:
        - dependency
        - converge
        - idempotence
verifier:
    name: ansible
