---
- name: Oracle JDK | GraalVM | Install
  when: java_rv_jdk_graalvm_is_install
  block:
      - name: Oracle JDK | GraalVM | Install | Get downloaded file stat
        ansible.builtin.stat:
            path: "{{ java_rv_jdk_graalvm_tarball_download_path }}"
        register: pv_ua_jdk_graalvm_downloaded_file_stat

      - name: Oracle JDK | GraalVM | Install | Newly Downloaded
        when: not pv_ua_jdk_graalvm_downloaded_file_stat.stat.exists
        block:
            - name: Oracle JDK | GraalVM | Install | Newly Downloaded | Download tarball
              ansible.builtin.get_url:
                  url: "{{ oracle_jdk_tmp_version_details.extras.graalvm.download_link }}"
                  checksum: "{{ oracle_jdk_tmp_version_details.extras.graalvm.checksum | default(omit) }}"
                  dest: "{{ java_rv_jdk_graalvm_tarball_download_path }}"
                  mode: "0700"
                  timeout: 300
              timeout: 300
              notify:
                  - Oracle JDK | GraalVM | Install | Unarchive the tarball

            - name: Oracle JDK | GraalVM | Install | Newly Downloaded | Remove Old Install Directory
              ansible.builtin.file:
                  path: "{{ java_rv_jdk_graalvm_install_path }}"
                  state: absent

        rescue:
            - name: Oracle JDK | GraalVM | Install | Newly Downloaded | Delete Downloaded tarball
              ansible.builtin.file:
                  path: "{{ java_rv_jdk_graalvm_tarball_download_path }}"
                  state: absent

            - name: Oracle JDK | GraalVM | Install | Newly Downloaded | Delete Install Directory
              ansible.builtin.fail:
                  msg: "Failed to download GraalVM JDK tarball. Check the above errors."

      - name: Oracle JDK | GraalVM | Install | Create install directory
        ansible.builtin.file:
            path: "{{ java_rv_jdk_graalvm_install_path }}"
            state: directory
            mode: "0700"
        notify:
            - Oracle JDK | GraalVM | Install | Unarchive the tarball

- name: Oracle JDK | GraalVM | Remove
  when: not java_rv_jdk_graalvm_is_install
  ansible.builtin.file:
      path: "{{ java_rv_jdk_graalvm_install_path }}"
      state: absent
