---
- name: Oracle JDK | Gradle | Get Downloaded File Stat
  ansible.builtin.stat:
      path: "{{ __java_rv_jdk_gradle_tarball_download_path }}"
  register: __java_rv_jdk_gradle_tarball_stat

- name: Oracle JDK | Gradle | Download
  when: not __java_rv_jdk_gradle_tarball_stat.stat.exists
  block:
      - name: "Oracle JDK | Gradle | Download | Download Tarball"
        ansible.builtin.get_url:
            url: "{{ __oracle_jdk_tmp_version_details.extras.gradle.download_link }}"
            checksum: "{{ __oracle_jdk_tmp_version_details.extras.gradle.checksum
                | ansible.builtin.default(default_value=omit) }}"
            dest: "{{ __java_rv_jdk_gradle_tarball_download_path }}"
            mode: "0700"

      - name: Oracle JDK | Gradle | Download | Remove Old Temporary Unzip Directory If Exists
        ansible.builtin.file:
            path: "{{ __java_rv_jdk_gradle_tmp_unzip_path }}/gradle-{{
                __oracle_jdk_tmp_version_details.extras.gradle.version[1:] }}"
            state: absent

  rescue:
      - name: Oracle JDK | Gradle | Download | Remove Tarball
        ansible.builtin.file:
            path: "{{ __java_rv_jdk_gradle_tarball_download_path }}"
            state: absent

      - name: Oracle JDK | Gradle | Download | Fail
        ansible.builtin.fail:
            msg: |+
                Failed to download {{ __oracle_jdk_tmp_version_details.extras.gradle.download_link }}
                Check the errors above.

- name: Oracle JDK | Gradle | Create Temporary Unzip Directory
  ansible.builtin.file:
      path: "{{ __java_rv_jdk_gradle_tmp_unzip_path }}"
      state: directory
      mode: "0700"

- name: Oracle JDK | Gradle | Unarchive The Zip
  ansible.builtin.unarchive:
      src: "{{ __java_rv_jdk_gradle_tarball_download_path }}"
      dest: "{{ __java_rv_jdk_gradle_tmp_unzip_path }}"
      remote_src: true
  notify: Oracle JDK | Gradle | New Install

- name: Oracle JDK | Gradle | Flush Handlers
  ansible.builtin.meta: flush_handlers
