---
- name: Oracle JDK | Apache Groovy | Get Downloaded File Stat
  ansible.builtin.stat:
      path: "{{ java_rv_jdk_groovy_tarball_download_path }}"
  register: java_rv_jdk_groovy_tarball_stat

- name: Oracle JDK | Apache Groovy | New Download
  when: not java_rv_jdk_groovy_tarball_stat.stat.exists
  block:
      - name: Oracle JDK | Apache Groovy | Download Tarball
        ansible.builtin.get_url:
            url: "{{ oracle_jdk_tmp_version_details.extras.groovy.download_link }}"
            checksum: "{{ oracle_jdk_tmp_version_details.extras.groovy.checksum | default(omit) }}"
            dest: "{{ java_rv_jdk_groovy_tarball_download_path }}"
            mode: "0700"
  rescue:
      - name: Oracle JDK | Apache Groovy | Remove Tarball
        ansible.builtin.file:
            path: "{{ java_rv_jdk_groovy_tarball_download_path }}"
            state: absent

      - name: Oracle JDK | Apache Groovy | Remove Temporary Unzip Directory
        ansible.builtin.file:
            path: "{{ java_rv_jdk_groovy_tmp_unzip_path }}"
            state: absent

      - name: Oracle JDK | Apache Groovy | Fail
        ansible.builtin.fail:
            msg: |+
                Failed to download {{ oracle_jdk_tmp_version_details.extras.groovy.download_link }} to
                   {{ java_rv_jdk_groovy_tarball_download_path }}
                Check the errors above and try again.

- name: Oracle JDK | Apache Groovy | Create Temporary Unzip Directory
  ansible.builtin.file:
      path: "{{ java_rv_jdk_groovy_tmp_unzip_path }}"
      state: directory
      mode: "0700"

- name: Oracle JDK | Apache Groovy | Unarchive The Zip
  ansible.builtin.unarchive:
      src: "{{ java_rv_jdk_groovy_tarball_download_path }}"
      dest: "{{ java_rv_jdk_groovy_tmp_unzip_path }}"
      remote_src: true
  notify: Oracle JDK | Apache Groovy | New Install

- name: Oracle JDK | Apache Groovy | Flush Handlers
  ansible.builtin.meta: flush_handlers
