---
- name: Oracle JDK | Apache Groovy | New Install
  block:
    - name: Oracle JDK | Apache Groovy | New Install | Remove old directory
      ansible.builtin.file:
        path: "{{ java_rv_jdk_groovy_install_path }}"
        state: absent

    - name: Oracle JDK | Apache Groovy | New Install | Recreate Install Directory
      ansible.builtin.file:
        path: "{{ java_rv_jdk_groovy_install_path }}"
        state: directory
        mode: "0700"

    - name: Oracle JDK | Apache Groovy | New Install | Copy new files
      ansible.builtin.copy:
        src: "{{ java_rv_jdk_groovy_tmp_unzip_path }}/groovy-{{ java_rv_jdk_groovy_version }}/"
        dest: "{{ java_rv_jdk_groovy_install_path }}/"
        remote_src: true
        mode: "0700"
  rescue:
    - name: Oracle JDK | Apache Groovy | Remove the zip
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ java_rv_jdk_groovy_tmp_unzip_path }}/groovy-{{ java_rv_jdk_groovy_version }}/"
        - "{{ java_rv_jdk_groovy_tarball_download_path }}"
