---
- name: Oracle JDK | Apache Maven | Get downloaded file stat
  ansible.builtin.stat:
      path: "{{ java_rv_jdk_mvn_tarball_download_path }}"
  register: java_rv_jdk_mvn_tmp_downloaded_file_stat

- name: Oracle JDK | Apache Maven | Newly Downloaded
  when: not java_rv_jdk_mvn_tmp_downloaded_file_stat.stat.exists
  block:
      - name: Oracle JDK | Apache Maven | Newly Downloaded | Download tarball
        ansible.builtin.get_url:
            url: "{{ oracle_jdk_tmp_version_details.maven.download_link }}"
            checksum: "{{ oracle_jdk_tmp_version_details.maven.checksum }}"
            dest: "{{ java_rv_jdk_mvn_tarball_download_path }}"
            mode: "0700"

      - name: Oracle JDK | Apache Maven | Newly Downloaded | Remove old install directory
        ansible.builtin.file:
            path: "{{ java_rv_jdk_mvn_install_path }}"
            state: absent

  rescue:
      - name: Oracle JDK | Apache Maven | Newly Downloaded | Remove tarball
        ansible.builtin.file:
            path: "{{ java_rv_jdk_mvn_tarball_download_path }}"
            state: absent

      - name: Oracle JDK | Apache Maven | Newly Downloaded | Fail
        ansible.builtin.fail:
            msg: |+
                "Failed to download {{ oracle_jdk_tmp_version_details.maven.download_link }}
                to {{ java_rv_jdk_mvn_tarball_download_path }}"
                Check the error above for more details

- name: Oracle JDK | Apache Maven | Create install directory
  ansible.builtin.file:
      path: "{{ java_rv_jdk_mvn_install_path }}"
      state: directory
      mode: "0700"

- name: Oracle JDK | Apache Maven | Newly Downloaded | Unarchive the tarball
  ansible.builtin.unarchive:
      src: "{{ java_rv_jdk_mvn_tarball_download_path }}"
      dest: "{{ java_rv_jdk_mvn_install_path }}"
      extra_opts: [--strip-components=1]
      remote_src: true
