---
- name: Minio | Molecule | Verify
  hosts: all
  gather_facts: false
  tasks:
      - name: Minio | Molecule | Verify | Import Roles for variables
        ansible.builtin.import_role:
            name: arpanrec.nebula.minio
            tasks_from: prerequisites.yml

      - name: Minio | Molecule | Verify | Get Latest Version
        ansible.builtin.set_fact:
            minio_version_details: "{{ lookup('arpanrec.nebula.version_db', 'minio',
                minio_rv_version=minio_rv_version) | from_json }}"

      - name: Minio | Molecule | Verify | Get version from shell
        ansible.builtin.command:
            argv:
                - "{{ minio_executable }}"
                - "--version"
        environment:
            PATH: "{{ ansible_env.PATH }}"
        register: minio_rv_tmp_version_shell_result
        changed_when: false

      - name: Minio | Molecule | Verify | Assert version is as expected
        ansible.builtin.assert:
            that:
                - "'version ' + minio_version_details.version in minio_rv_tmp_version_shell_result.stdout_lines[0]"
            fail_msg: >
                Minio version is not as expected.
                Expected: {{ minio_version_details.version }}
                Found: {{ minio_rv_tmp_version_shell_result.stdout }}
            success_msg: >
                Minio version is as expected.
                Expected: {{ minio_version_details.version }}
                Found: {{ minio_rv_tmp_version_shell_result.stdout_lines }}

      - name: Minio | Client | Molecule | Verify | Get Latest Version
        ansible.builtin.set_fact:
            minio_client_version_details: "{{ lookup('arpanrec.nebula.version_db', 'minio_client',
                minio_client_rv_version=minio_client_rv_version) | from_json }}"

      - name: Minio | Client | Molecule | Verify | Get version from shell
        ansible.builtin.command:
            argv:
                - "{{ minio_client_executable | basename }}"
                - "--version"
        environment:
            PATH: "{{ minio_client_executable | dirname }}:{{ ansible_env.PATH }}"
        register: minio_client_rv_tmp_version_shell_result
        changed_when: false

      - name: Minio | Client | Molecule | Verify | Assert version is as expected
        ansible.builtin.assert:
            that:
                - "'version ' + minio_client_version_details.version
                  in minio_client_rv_tmp_version_shell_result.stdout_lines[0]"
            fail_msg: >
                Minio Client version is not as expected.
                Expected: {{ minio_client_version_details.version }}
                Found: {{ minio_client_rv_tmp_version_shell_result.stdout }}
            success_msg: >
                Minio Client version is as expected.
                Expected: {{ minio_client_version_details.version }}
                Found: {{ minio_client_rv_tmp_version_shell_result.stdout_lines }}
