---
dependency:
    name: galaxy
    enabled: true
    options:
        ignore-certs: false
        ignore-errors: false
        role-file: requirements.yml
        requirements-file: requirements.yml
driver:
    name: docker
platforms:
    - name: debian_role_ssh_hardening_docker
      hostname: debian_role_ssh_hardening_docker
      image: docker.io/library/debian:bookworm
      pre_build_image: true
      volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:ro
      privileged: true
      provider_raw_config_args:
          - "--sysctl"
provisioner:
    name: ansible
    playbooks:
        converge: converge.yml
        prepare: prepare.yml
        verify: verify.yml
    vvv: true
    env:
        ANSIBLE_VERBOSITY: 5
    inventory:
        group_vars:
            all:
                linux_patching_rv_install_devel_packages: false
scenario:
    name: role.ssh_hardening.docker
    create_sequence:
        - dependency
        - create
        - prepare
    destroy_sequence:
        - destroy
    converge_sequence:
        - converge
    test_sequence:
        - dependency
        - destroy
        - syntax
        - create
        - prepare
        - converge
        - idempotence
        - destroy
verifier:
    name: ansible
