---
- name: Terraform | Prerequisites
  ansible.builtin.import_tasks: prerequisites.yml

- name: Terraform | Create install directory
  ansible.builtin.file:
      path: "{{ terraform_rv_install_path }}"
      state: directory
      mode: "0700"

- name: Terraform | Get Version Details
  ansible.builtin.set_fact:
      terraform_tmp_version_details: "{{ lookup('arpanrec.nebula.version_db', 'terraform',
          terraform_rv_version=terraform_rv_version) }}"

- name: Terraform | Get downloaded file stat
  ansible.builtin.stat:
      path: "{{ terraform_rv_tarball_download_path }}"
  register: terraform_rv_tmp_downloaded_file_stat

- name: Terraform | New Download | Create download directory
  ansible.builtin.file:
      path: "{{ terraform_rv_tmp_install_cache_dir }}"
      state: directory
      mode: "0700"

- name: Terraform | New Download
  when: not terraform_rv_tmp_downloaded_file_stat.stat.exists
  block:
      - name: "Terraform | New Download | Download tarball"
        ansible.builtin.get_url:
            url: "{{ terraform_tmp_version_details.download_link }}"
            checksum: "{{ terraform_tmp_version_details.checksum | default(omit) }}"
            dest: "{{ terraform_rv_tarball_download_path }}"
            mode: "0700"
  rescue:
      - name: Terraform | New Download | Fail | Cleanup
        ansible.builtin.file:
            path: "{{ terraform_rv_tarball_download_path }}"
            state: absent

      - name: Terraform | New Download | Fail | Fail
        ansible.builtin.fail:
            msg: Something went wrong, check the errors above

- name: Terraform | New Download | Unarchive the tarball
  ansible.builtin.unarchive:
      src: "{{ terraform_rv_tarball_download_path }}"
      dest: "{{ terraform_rv_install_path }}"
      remote_src: true
