---
dependency:
    name: galaxy
    enabled: true
    options:
        ignore-certs: false
        ignore-errors: false
        role-file: requirements.yml
        requirements-file: requirements.yml
driver:
    name: docker
platforms:
    - name: debian_role_telegram_desktop_default
      hostname: debian_role_telegram_desktop_default
      image: docker.io/library/debian:bookworm
      dockerfile: Dockerfile.j2
      pre_build_image: false
provisioner:
    name: ansible
    vvv: true
    env:
        ANSIBLE_VERBOSITY: 5
    inventory:
        group_vars:
            all:
                ansible_python_interpreter: /usr/bin/python3
    playbooks:
        converge: converge.yml
scenario:
    name: role.telegram_desktop.default
    create_sequence:
        - dependency
        - create
    destroy_sequence:
        - destroy
    converge_sequence:
        - converge
    test_sequence:
        - syntax
        - dependency
        - create
        - converge
        - idempotence
        - destroy
verifier:
    name: ansible
