---
# Group Name : Primary Group of the user
# Type: String
# user_add_rv_user_primary_group:

# Group ID : GID for primary group
# Type: int
# user_add_rv_user_primary_gid:

# Username
# Type: String
# user_add_rv_username:

# User ID : UID
# Type: int
# user_add_rv_uid:

# Clear text password for the user
# Type: String
# user_add_rv_password

# Groups : Extra groups for user
# Type: List<String>
user_add_rv_user_extra_groups: []

# Public key for remote ssh access
# Type: List of String
# user_add_rv_ssh_access_public_key_content_list

# Commands user will be able to run without password
# Type: List<String>
user_add_rv_user_nopasswd_commands: []

# Default shell for user
# Type: String
user_add_rv_user_default_shell: /bin/bash
