---
- name: Minio | Client | Prerequisite.
  ansible.builtin.import_tasks: prerequisites.yml

- name: Minio | Client | Get Release.
  ansible.builtin.set_fact:
      minio_client_version_details: "{{ lookup('arpanrec.nebula.version_db', 'minio_client',
          minio_client_rv_version=minio_client_rv_version) | from_json }}"

- name: Minio | Client | Download gpg signature.
  ansible.builtin.get_url:
      url: "{{ minio_client_version_details.download_link }}.asc"
      mode: "0755"
      dest: "/tmp/minio-client-{{ minio_client_version_details.version }}.asc"

- name: Minio | Client | Download binary.
  ansible.builtin.get_url:
      url: "{{ minio_client_version_details.download_link }}"
      checksum: "{{ minio_client_version_details.checksum | default(omit) }}"
      mode: "0755"
      owner: root
      group: root
      dest: "{{ minio_client_executable }}"

- name: Minio | Client | Verify binary.
  ansible.builtin.command:
      argv:
          - gpg
          - --verify
          - "/tmp/minio-client-{{ minio_client_version_details.version }}.asc"
          - "{{ minio_client_executable }}"
  register: minio_client_verify_gpg_signature_res
  failed_when: minio_client_verify_gpg_signature_res.rc != 0
  changed_when: false
