---
- name: Minio | Prerequisite | Gather root facts.
  ansible.builtin.setup:

- name: Minio | Prerequisite | Get system 1 PID Details.
  ansible.builtin.command: ps -p 1
  register: minio_rv_tmp_one_pid_shell_result
  changed_when: false

- name: Minio | Prerequisite | Assume system is not in systemd.
  ansible.builtin.set_fact:
      minio_rv_init_system_systemd: "{{ minio_rv_tmp_one_pid_shell_result.stdout_lines[1] \
          | split(' ') | last == 'systemd' }}"

- name: Minio | Prerequisite | Write gpg key.
  ansible.builtin.copy:
      dest: "/tmp/minio-gpg.asc"
      content: "{{ mini_gpg_key }}"
      mode: "0644"

- name: Minio | Prerequisite | Import gpg key.
  ansible.builtin.command:
      argv:
          - gpg
          - --import
          - "/tmp/minio-gpg.asc"
  register: minio_import_gpg_key_res
  changed_when: "'imported' in minio_import_gpg_key_res.stdout"
