---
gitea_systemd_service_name: gitea-{{ gitea_cluster_name }}.service

gitea_executable: /usr/local/bin/gitea-{{ gitea_version_details.version }}

# yamllint disable-line rule:line-length
# SSL Certs file should be exactly as it is, https://docs.gitea.com/installation/database-prep#postgresql-tls. (This doesn't work). These needs to be set via env variable PGSSLROOTCERT, PGSSLCERT, PGSSLKEY. https://github.com/go-gitea/gitea/issues/32635
gitea_config_db_pg_ssl_root_cert_file: "{{ gitea_service_user_home_directory }}/.postgresql/root.crt"
gitea_config_db_pg_ssl_cert_file: "{{ gitea_service_user_home_directory }}/.postgresql/postgresql.crt"
gitea_config_db_pg_ssl_key_file: "{{ gitea_service_user_home_directory }}/.postgresql/postgresql.key"

# defaults to AppWorkPath/custom
gitea_custom_directory: "{{ gitea_working_directory }}/custom"
# yamllint disable-line rule:line-length
# For CustomConf https://docs.gitea.com/administration/config-cheat-sheet#use-environment-variables-to-setup-gitea, Don't change this path, so that we don't have to ever inject this file anywhere, it's default.
gitea_app_ini_file: "{{ gitea_custom_directory }}/conf/app.ini"

gitea_http_key_pem_file: "{{ gitea_custom_directory }}/ssl_cert.pem"
gitea_http_cert_pem_file: "{{ gitea_custom_directory }}/ssl_key.pem"

gitea_secret_key_file: "{{ gitea_custom_directory }}/gitea_secret_key"
gitea_internal_token_file: "{{ gitea_custom_directory }}/gitea_internal_token"
gitea_oauth2_jwt_secret_file: "{{ gitea_custom_directory }}/gitea_oauth2_jwt_secret"
gitea_lfs_jwt_secret_file: "{{ gitea_custom_directory }}/gitea_lfs_jwt_secret"

gitea_app_data_directory: "{{ gitea_working_directory }}/data"
gitea_lfs_directory: "{{ gitea_app_data_directory }}/lfs"
gitea_repository_root_directory: "{{ gitea_app_data_directory }}/gitea-repositories"
gitea_git_home_directory: "{{ gitea_app_data_directory }}/home"
gitea_sqlite3_db_file: "{{ gitea_app_data_directory }}/sqlite3.db"

gitea_log_root_path: "{{ gitea_working_directory }}/log"
gitea_log_file: "{{ gitea_log_root_path }}/gitea.log"

gitea_teabot_gpg_key: |+
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    mQINBFsvDSkBEADtyFKGhQ/sh9KmVAzivJfMGbasytWkZNdIrwCoxSTEijl2QLyi
    E8b5xEOK2+9b3OXF+Nbm+tdfVCaKfoDhXdglxvENSdXA0mKxt4RhKxXAkWHrLfeA
    A4RbUj0ndfpJWpoRoEPZTP2a8UXOctUVQP+JzC+D028nawzpSVrXN7UYkszJ5j06
    oR6+ZMjpEMbPRnOWRuaJONPvBuTHGDSsD3UPJlWyeUv7+GmcVJzjc8uq1HeX/5Ap
    NTrESldIDPgcxfTWhscj1+s8gvW5SqcNQnWSIUtI+Bi2sW9ibj9XlkFJMU7QFV+S
    1uF9D8lynZCSDIjnsqSuX3TMgr2CPk7+0eLNFAVrrTUbGwcoyge3d8osJD5PS3z6
    COwDlzAXRJECScRo1ynxCxJTLVf6JoGQEFzVc5HSlM8Lx1zm/Al+AYdhdToCQNDF
    vLLuHkMqh3OLG3yxS142BUHDrd0KaiY+sxoUQjVjo7PHpLZRJKGZCxSS6vPr9I+o
    OTDO2h7rWdTtodmkSz9+NnUD1cGYWwL8j4Cpi4yozg+8Gbtywnm/q0TPMYhyiBbn
    hU+sowfmo1RPn2aQnxSS55L7cMTNzP95cU4FQDNzYhget9X5UJJPWdSRcknykMcQ
    oAo0IfswMDC7LWf8uObZo/0DQeGBVBx2y/+Ir9dt5MhcrmO/U+fCF+O2xwARAQAB
    tBhUZWFib3QgPHRlYWJvdEBnaXRlYS5pbz6JAlQEEwEIAD4CGwMFCwkIBwIGFQoJ
    CAsCBBYCAwECHgECF4AWIQR8nmgVJZRoiGLWKvYtmugG7BWS4gUCaFibvwUJDwrC
    FgAKCRAtmugG7BWS4vclEADM8a/DsZVP+F32MM2D6AYvnrDguMn1TegyQ18G6+Hb
    y6d1NpL8gQ4OJkMp1LMvEGltqhMrWCbg+uMfQvYnum5js8fVZ18sGChRBQ//7s/Z
    2Tf7dP3jwiuMPVEJ7Ft4X9oS6myxO6qxJwV3ln65kYmoU5EcRo8kwB+HwVrQvofe
    XK/tiqCw5BKl0kjBTf+bfhUzTEiJwqIM0nv0JkuT7UKkOdlx1nl8aEgtGrhIzDxv
    meJWaEFIwCfA8m77/YKaHu89uObvoD3hwjyaTb41r21H0ABrM+h22S73f/XUQ3Wu
    6LrZ0ytN7sQu0rn6LF247ZUKLiKFw47d4jB/v1wlC07WIHQQPQo1kf4SxyrGOuZH
    4huK3fcegU+h6kVkD3BcjpFOHgmFBGgR6j692XoMjiegcrClGC23ruG5O2ztYCzX
    ldGkW1zc0BOPIWRPgnijgGXvMMuz5n8IR4xET+n/3/9uQw4qbo2hj3NsKHCV11BQ
    mUVbOfiU9mYhWYVDzDsVL3dgMY3QdZP6ikSA0PjM0WwdslJGiyW0oJz6uPta1xSX
    g8k0OtrnKxICIZwSx/8/prK709qd0mk2iu4BC/BxZeLzXl6dBM7Y9B3XnXK1M+D+
    6Qc0Quuh4YQM5GjvTekT2j8xE/jlQDIwKXPREygUqlpydi+/XquNSnxXAmnB21sf
    dIkCVAQTAQgAPgIbAwULCQgHAgYVCgkICwIEFgIDAQIeAQIXgBYhBHyeaBUllGiI
    YtYq9i2a6AbsFZLiBQJmdoOpBQkNKKoAAAoJEC2a6AbsFZLiIWMQAJvGFgbLF+LU
    IyY4MjfwpBFERNfhffnMdWmGcsj0A9Fx8b+ad9ny1iOYK/KdenLAcQ/m/EbbbBU5
    VjdyIHo410eeOj6VzE8xAqFA1LOX4Qdui54NF+lyYuRhGBOrke6NtW8+KJMmAflB
    HrWeHIPtXF2PaBsFf9xxehWT4K33+fhDiYUaK5vjTse9M/QiF19gPZp0mvDmX98m
    8KSm6e9+86ja0hlxUcDRg+0HL5/9TizK/usG3Jr+T5EO4/Zqot+xoXBtxB3IR8Wn
    6cHuoMrai2bHyfXFgpfJHHpUt+Ffaz5/yUq8wUDuVdNRHfDWhx1x6ZwiK2VlVndc
    UacSRXtgToxYzfn3JhTzHRpJLEKu5CNNnJHL1ScQP/kn6r+rJJF9XqxIoGuY+Ukc
    bpO6q1V4ALnvg/HtSazGu1lLHElwUynYcdo36tGTu8xvw+l6wCrjvNEOLYCnNdRC
    Z57tPW6DJSyyK22SUq3iiETyapS5AyzG4+nh8GLphHciLthYyALSJbPXkXD83B5f
    G3grTbgz4odWTvgPOUfYDac5Sjo2mTPtAWXrRR6lX7SyZfHEosniiVY+rsqvcs4/
    3AZ+d+XrovBF1DVV7wqcUZkNC3Ur9BnyOZhfl8Ic6SWQr16L6AJWJsdXykD0FblX
    ySk2CUBGx5a//AU9U3d55jj4r74+6ioxiQJUBBMBCAA+AhsDBQsJCAcCBhUKCQgL
    AgQWAgMBAh4BAheAFiEEfJ5oFSWUaIhi1ir2LZroBuwVkuIFAmKzBw8FCQtGYOYA
    CgkQLZroBuwVkuKe3A/8DdmL/zjjJojohu5aipCENHuGphjpFnZV4AJZ+gSYQ90w
    mTJ7F+IgDj2Wzl8a7Vj6Dtt9o98t2icj1iHiXqR8PKFpCeGEXlUiGjqO3zYbh6VC
    g4u6qoL/XHcss9TRdGqUO9oSnuuJiZkkbobsm+8VOKDtZ6wKSRVxmheVRTmK678m
    tpmwqZ7bOqKSCdxhpd3cCq3xr46tAbokK6h3bPJYUFjEgkNUtw7r59qn+q521ueW
    cQ+qTebZa8sOeq8NhNztBVzDfSKZVd1lmLyhEmEgB97oB3IyQ1z7tE8t9qKdXo1P
    g78hTs0A7vd30nPurXdumUNov2zpKlBefEJFt9VQzuBvwd22A2f+O8FyMOKK487M
    eIw3l/sYKWLVuEq+v//z09TuBGDiuaCRkkEwn4S0XEXKCuEnamh4A6clHfCj2/xP
    QEO8fTcCa/35aNmDewp2G1cuSGNbCB57zKEpjvRoBopre0jmxPn5ShtmJRUQUvlx
    BA+BXhgdqqlaJ0BSwF381rjJSIoxT9CpvcSG4D8ToOtsBJWx+1xmObcndDesd34S
    ntYs82llv+vZ50E2zwdzoYDqoBtVMhlL0lYCWNn4+Ahil+fU1tEgjq+9J2XqrlKA
    4f6+LzWcsDoQtPMd+8tDysqIOENmb5dRy8t56UyY3NaXBYTbf9mhBSMsZwP21gGJ
    AlQEEwEIAD4CGwMFCwkIBwIGFQoJCAsCBBYCAwECHgECF4AWIQR8nmgVJZRoiGLW
    KvYtmugG7BWS4gUCXvKlFgUJB4X+7QAKCRAtmugG7BWS4nDAEADttD9mPkKlrUhp
    JxPbzblstIsv5OvTGjemjrTJc6UTHsjUe1eZ3+QsHN0TGZEP0WigA1hseA4j+7/S
    8CeYeAf7K7LS4KVGJ9AlZC1xEuIIHnQURNWOubEDuRkuYvK2HZ5sEQfRbgW6q8bL
    AHGvsqQG7fw8elwpERI5y0qDZZhXiVNqMmeaCnLVp5GTS6j7+gT7ySqwun+02K5U
    jtUjhDdyu4fyPctPcNkI2kzcXUnvTeAOPZSgdvmF8SlG27K0pXn+aeGopLamt2dD
    2nXQgwECMYfu9vFEEqn9TN899eVeEWeLMBmBWDMfE3NPDTitKyGwQ1XGa+SRt3kV
    uIClZVa8hiCdl0AZcReHmUK9L0i5hggQQfeoPofAJUbM4PzjKjaJ/P328T5o/Rz7
    QQaRUudPPdTvoxi4DojynBwqjg0gpagywiNfzH8LOTVFXjRhbmhy8w1zs5z4rCIZ
    Zo3fC6Dk2MwgcJEolbCC+7iEu/R7kziTisMA2l0TTYIjuaFveTHorS6VfzK/xdq3
    OhY6YEEDHnch5mnQ3Lxms9z6H2GCFnVeXJR90qNDy91lGFtCQ5ks4xzW1NqNDJRl
    Wn4+sw7rD/41scEeVZGWKuohm3cQr39OX1W8xo1eesk6wniHmwr5x6RZi6tVuKi+
    0UkXu8E3ez2rde3BicdWESpvbFdMzIkCVAQTAQgAPhYhBHyeaBUllGiIYtYq9i2a
    6AbsFZLiBQJbLw0pAhsDBQkDwmcABQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAAAoJ
    EC2a6AbsFZLiw44P/0MpkiOcklDmT3yGJPzVotanLpzzwxLRFACBlecNo5RfZlwn
    4lnVu4ZAfcKHdCgQAtHtMqEjz5Ue6PLuDCdIxSVlK1WsegCKT/jzl36TTw035nlo
    1ahgrqVx3XU4WLq4/LwOASfZZQcV9BR6wH8WE6cbxbsNDPgeIygwUwAoQR54D07Z
    twtbu6QXU5RXBgGhZAap0S59buGITtY4B6hhjMQkcBkafFDdskrgZjH9GFqvS1qc
    hgWFfnxK0Q1ZT1qXDgQJR2ZALf4X5u7zWSOcPRMNA/2rA+Oh2jyNnkxAkMpwA6OT
    iyaA0xo3lups1vx/CYGCQurBpAHtKITVaVx5PGoHpJN1QEBJrFdcC8xiVd25qUYM
    SbjAVRXI9EFSPy5JZBlsYeFnQ0QwWnIQCRAQe0DI9oZkk7BAuptCdMRXo+GO85c6
    w6nMbuKOiakE6djyXst6Vle0pCOT81F8G+DF8crDl3VKE6IPmq5N0XX0lRYDL7Xk
    NUaqO0iEA/gtfWAYtSUWiHwcnzW5C6fHMRa8sG0R1CluPOabhAs2pQnaFAwGDRyF
    RYcfmKro9267I8eiydq1z8y8tl3BXPYWsvZgZuLF5ahgNjYB9XRQZWMXVboraiiw
    QsCHeMzG/2Uas/idPQfA1TU0CDHn9/LktcnScN7BHQEi5lkxmadLfzn8uNtmuQIN
    BFsvDSkBEADYL0eMn3ZZfk5EV+Zb4FmBZw4+/3nhMInX6PMzu/3WxczcORQtgzN0
    /VQ19OHhsv8I29Pr+SPOaDm0ASdMgzNYq//qdKYgQsjAaGHzGcgomGYqV9Bix0Mp
    K5yuo+IKD6q5cQAeqFD/h82+TCiW7G+y2Hxgeu9MAvvTp8pU4pk1WbNrgTZvhOxw
    brRv2AGzxsUxgqyj5ox30dvIo8n5WsoXpl0OOlpLRg9U7uBNMmUu12TOlEE4HFO5
    xjRO5EwfKWAHP6EUGk0JLTfAMQ/AMZa5WeWqeWzV/Pni6/RpuAmY2SEu/+gro1Xq
    ytkeQCV877WcC0VT/C1QihuvNGy3ovv7j4Qroh2L6NgeAyym01OqI5bV4+EJ+6cI
    bC4ohQAfj6nhY/E/6bkYmzs1uwMvSULVjFAtRD8m3lypy0xHTX64N5yICi65WVTu
    FUqDQiFfjP9Si2BS08mBM5lCOC/FwtkAMC0IRfNSYNdAjo0BDh59Yana5vfW1VNN
    CHD7ZG08cOBaHhg+qiZK8t28UX6rkxDxghk2HEw3sxKEW7pJoHc5OiltL5/4Oq2A
    VC/Sm63VeeDlfVu8qj4xMikyjVG0c86XOpoCDxlzmKbG5YYiUGER1WCTB9uuJ3e6
    AO+3wAJ8p2s8NB6f3vWeeyzZhtsm41Amge/sZggSQGqytjPydTxGxQARAQABiQI8
    BBgBCAAmAhsMFiEEfJ5oFSWUaIhi1ir2LZroBuwVkuIFAmhYm38FCQ8KwdYACgkQ
    LZroBuwVkuJ0fw/9EB1xR6dplLHovkaxkB4HOqzyM9UBo40A16lwcppcRhFuK+fM
    PNpEdwZJ1DhEvIbm1uNAtxolPqdCXSHuLRJXg28/mkcjdkSeJ4u+XsDObzLDz2rC
    1BSwlQ+QrWH7LzjHN2TWRnZLwC82b0QXIR4V3Wxi3cVRjV7kyNu8BctQhN3kbO+x
    H/DZyj8/ZgURLv4izbuF5OBxrisRlbP0JUETdQC5CmSgMBAaCP5UzXwpT/rw4SQz
    3jEOn+qeb8+elDG9FksdOH+PxTxdUtYSohRRj+GeJrT3kJbluv//gkBmGG2u3deI
    YfsdGf37PiKJhoR5mM2Or1BtJKNv6vSKyRlLad/ZAmPhlTQgphDCqYlGEczY90O1
    jbetbAtZWrKOh+1lbNG0QZIQnHtbtDA4vnipQeMpOT/9Y9XJa0bPonWIoX+SqJx0
    axc4DH5jKdt7/V0atZiyB7uZHwOAzQ3Fm3rFWBB7wDuVHaWJ9rUK/onsx4ZKOJmw
    ClWMv26YLlQALYBdH07dntRI2lZteRc0Va5xW/fMSFPMDzYYDzr6PuLcWCd+2tgp
    uhDnGshLkx13wzGKfoYV0ClNSuEEWbhwjIyRjqBh6xYBK+3a8RXOZesoMF31nXjO
    ibJCQOKZox887RZdN8L0KpR6GVX/QTQDzsrsNxD/m4F6iVJxs/ycYN31GWq5Ag0E
    Wy8NsQEQANo50UmRXZHAMMoH/AaMhvR7q1ahW9LeUkWRxIxSJesJnb5ZNdyrM78s
    0SfvCBC90ELXcEymQDGE/R2pnJb8Iohfdv9dh8LEytSI5/2sgLFphxYV76pRGirZ
    v9/TI+jOG+sD5Jeb8v02KMY9wgxpfIFkB6P0ZmDnA5etU8LMLeLqJ1JuHzvVfMdf
    ZocW2qegg7IehIeuEsV0ZMl2mNVD63eFf07JcgbC8+S+bICFVU75zYrUgJxocu+w
    sFIr9w5L6CupXO/ybx9c3+dP797nqroUwAXjLoXQ+Vc+2auhmDkpA4f4Dwn4AXi9
    Fv76VklS8kAtHZAveMsTfUeUhynGnvviBRYUmtwjT4gS4Wf+nZdytTFeKydAmPvk
    W2DR3a5kBQPeR6Ykn6nDhgWVOWH1fhK5bFamRagTD+3nWbYE/ZClvDT0HS3ZuGgp
    cwQE55CNMIAKM6thQWnBaLLjRFFQlmqer2idS9HCXiAu5Mzpqd0/1v5JRAn8R3px
    CKB+V5bCLoBzALXZ1swGb/C5y3wqOxbLlGVw+z4Tb2rzSVHUNhGigvw0stPvuiJd
    cCr7dukT2jDNCbRHQjtwDKF1bX6i6dBK+BQVKR1ejrWlYZZ6joR4ejvwJZl/M/dD
    pHP7vlAbcIYHFxcjN6APSShACLYRQYvfO9X6wQG10vGfWCREi6UNABEBAAGJBHIE
    GAEIACYCGwIWIQR8nmgVJZRoiGLWKvYtmugG7BWS4gUCaFibfwUJDwrBTgJACRAt
    mugG7BWS4sF0IAQZAQgAHRYhBMxksdtnq77sqyS2RV/DRjKXU/SwBQJbLw2xAAoJ
    EF/DRjKXU/SwxVMP/22vseRNCJ75I86sv/oEmvX9wCFTle/nwiQyy4GY87q6qYxq
    vmC+9t5tpp+msHsyMrdvanBN5oe+dKR5EOozOkRaLLewE3VLXB51ecQ6YZgHwJPI
    POBXcOYYdue8KZC/1qC2ISBoapHXFpkKRRCaOFMhWekBPLHXiRmDFwtiEpjJsjXD
    titk8lwYS38Q1RlBE0ppzb+278aqI2dnSmkJzSXs31k6huiqDMFcoYNtgn3tY7xe
    caqscrQINRVqjaOL7F3puL1otdvSw15EZ44pWpodiDY0D8p2c9NCPwmeZJpmam8U
    kmIteIH/OM1ai5g801FCJ0aGMdiUeA3P+YKREEeE6GI/DPa6LXkZKXx1R5w0yQlq
    if700CYDYvs3Qnk8DVkHjLCuBzVlKPF1HFMYZWszQf7ZHggsD+ARhZE8vASk56Rf
    hWVzYwRqNID54aUFUX9BvkHz67gB6DCzPUjL7JjEn+rFJLbHANW8jW62J9R8X8Be
    AzkW9bX7cqaloxOmv/4oe1Qh2Qz8NPrYn2P5oJNzJfAAWWWLYWxu9kEcSiKv8Sol
    0WPGFdedmZvznDb94lNqlBDmXEDN66tGuG6uX4CL5w1KkkL76MC6wgnzqYDuJk/I
    SJzYb3eK9zKiWEYmeR5QGVMm6LpKmTjw1weU2X4feTA1JP4MgiUcrlHEbufcsbkQ
    AKShj2lhNYgZALrLdr/Nxu1eN/TCQgRbwEB2Swa3oDzCcM35hex11KaFoOoR7NYo
    F+V4E5RIeyeindJhI2g73qGJb0s9bxKQ02rPYKuciMdA+Kdsb3ZWJXJA8R2fhYjH
    bG1c5rXJMMHJBa+ZRNLk0k8qJAGylFcIlm/mTMF+zLyF/n5YtYp9kxcX6sQJAowd
    +cVgrD5C3l22ZWuoiessWPHYsy9TeWhCWsXRRTylXWpNiH8zROC6rFH/MSfMvAJN
    e7/g6gfNyKd3AN8oTq6xL8bOoGX1HrNStAIcfnr7bffzc56MB/mLtoYlz0p36qpD
    Y6Gf3bQZXwWqTbe9GcZx2D5uwoR7eEMT8A5XtXRDxmwANXBgGp+6Rm1C7bz/w7W7
    BK6rsrizy3REGbOp2POMf4CYkaPLmpbk4oF+12WVRRKnYA4ozYcOj687zvO2YF36
    ApaSz0bQ03XNBebHpedC2MbU8b4vFf8xOdXc9r3jx9OyDaoE/SxlQ05xylab4jsN
    /vuJcJknqSiEopj5u2e9U/qg3B/SN6a9LVXx6ZWtRSPmYu9CqsGMiUkEpD/FTc7B
    7jf9rOJdz88tKBQT3Y+Y/mGB2PRpGCSIyms5Wo9l4SYj3RF9o0dGXGJ6DgySXgll
    7tcCQ4yof+HCQKzZLeU+3N4p6Ar2sgAtIrgbvjixsIIP
    =tFwr
    -----END PGP PUBLIC KEY BLOCK-----


gitea_default_config:
    - { section: DEFAULT, option: APP_NAME, value: "Gitea Easyiac" }
    - { section: DEFAULT, option: RUN_USER, value: "{{ gitea_service_user }}" }
    - { section: DEFAULT, option: RUN_MODE, value: "prod" }
    - { section: DEFAULT, option: WORK_PATH, value: "{{ gitea_working_directory }}" }

    - { section: server, option: PROTOCOL, value: "{{ gitea_protocol }}" }
    - { section: server, option: APP_DATA_PATH, value: "{{ gitea_app_data_directory }}" }
    - { section: server, option: DOMAIN, value: "{{ gitea_domain }}" }
    - { section: server, option: HTTP_PORT, value: "{{ gitea_http_port }}" }
    - { section: server, option: SSH_DOMAIN, value: "{{ gitea_ssh_domain }}" }
    - { section: server, option: ENABLE_ACME, value: "false" }
    - { section: server, option: DISABLE_SSH, value: "false" }
    - { section: server, option: SSH_PORT, value: "{{ gitea_ssh_port }}" }
    - { section: server, option: SSH_LISTEN_PORT, value: "{{ gitea_ssh_port }}" }
    - { section: server, option: START_SSH_SERVER, value: "true" }
    - { section: server, option: OFFLINE_MODE, value: "true" }
    - section: server
      option: ROOT_URL
      value: "{{ gitea_protocol }}://{{ gitea_domain }}:{{ gitea_http_port }}"
    - { section: server, option: LFS_START_SERVER, value: "true" }
    - { section: server, option: LFS_JWT_SECRET_URI, value: "file:{{ gitea_lfs_jwt_secret_file }}" }
    - { section: server, option: SSH_AUTHORIZED_KEYS_BACKUP, value: "true" }
    - { section: server, option: SSH_AUTHORIZED_PRINCIPALS_BACKUP, value: "true" }

    - { section: lfs, option: PATH, value: "{{ gitea_lfs_directory }}" }

    - { section: security, option: INSTALL_LOCK, value: "true" }
    - { section: security, option: SECRET_KEY_URI, value: "file:{{ gitea_secret_key_file }}" }
    - { section: security, option: INTERNAL_TOKEN_URI, value: "file:{{ gitea_internal_token_file }}" }
    - { section: security, option: DISABLE_GIT_HOOKS, value: "false" }

    - { section: oauth2, option: ENABLED, value: "true" }
    - { section: oauth2, option: JWT_SECRET_URI, value: "file:{{ gitea_oauth2_jwt_secret_file }}" }

    - { section: service, option: ENABLE_NOTIFY_MAIL, value: "true" }
    - { section: service, option: DISABLE_REGISTRATION, value: "true" }
    - { section: service, option: REQUIRE_SIGNIN_VIEW, value: "false" }
    - { section: service, option: ENABLE_BASIC_AUTHENTICATION, value: "false" }
    - { section: service, option: ENABLE_PASSWORD_SIGNIN_FORM, value: "true" }
    - { section: service, option: ENABLE_CAPTCHA, value: "false" }
    - { section: service, option: REQUIRE_EXTERNAL_REGISTRATION_CAPTCHA, value: "false" }
    - { section: service, option: REGISTER_EMAIL_CONFIRM, value: "true" }

    - { section: openid, option: ENABLE_OPENID_SIGNIN, value: "false" }

    - { section: actions, option: ENABLED, value: "true" }
    - { section: actions, option: DEFAULT_ACTIONS_URL, value: self }
    - { section: actions, option: STORAGE_TYPE, value: local }
    - { section: actions, option: ARTIFACT_RETENTION_DAYS, value: 7 }
    - { section: actions, option: ZOMBIE_TASK_TIMEOUT, value: 10m }
    - { section: actions, option: ENDLESS_TASK_TIMEOUT, value: 1h }
    - { section: actions, option: ABANDONED_JOB_TIMEOUT, value: 1h }

    - { section: log, option: ROOT_PATH, value: "{{ gitea_log_root_path }}" }
    - { section: log, option: MODE, value: "console,file" }
    - { section: log, option: LEVEL, value: Warn }
    - { section: log, option: ENABLE_SSH_LOG, value: "true" }
    - { section: log, option: logger.access.MODE, value: "console,file" }

    - { section: log.file, option: FILE_NAME, value: "{{ gitea_log_file }}" }

    - { section: cron, option: ENABLED, value: "true" }
    - { section: cron, option: RUN_AT_START, value: "true" }
    - { section: cron, option: SCHEDULE, value: "@midnight" }

    - { section: cron.update_checker, option: ENABLED, value: "true" }

    - { section: cron.cleanup_actions, option: ENABLED, value: "true" }
    - { section: cron.cleanup_actions, option: RUN_AT_START, value: "true" }
    - { section: cron.cleanup_actions, option: SCHEDULE, value: "@midnight" }

    - { section: cron.delete_old_actions, option: ENABLED, value: "true" }
    - { section: cron.delete_old_actions, option: RUN_AT_START, value: "true" }
    - { section: cron.delete_old_actions, option: SCHEDULE, value: "@midnight" }
    - { section: cron.delete_old_actions, option: NOTICE_ON_SUCCESS, value: "true" }
    - { section: cron.delete_old_actions, option: OLDER_THAN, value: 24h }

    - { section: cron.deleted_branches_cleanup, option: ENABLED, value: "true" }
    - { section: cron.deleted_branches_cleanup, option: RUN_AT_START, value: "true" }
    - { section: cron.deleted_branches_cleanup, option: SCHEDULE, value: "@midnight" }
    - { section: cron.deleted_branches_cleanup, option: NOTICE_ON_SUCCESS, value: "true" }
    - { section: cron.deleted_branches_cleanup, option: OLDER_THAN, value: 24h }

    - { section: repository.signing, option: SIGNING_KEY, value: default }
    - { section: repository.signing, option: SIGNING_NAME, value: gitea }
    - { section: repository.signing, option: SIGNING_EMAIL, value: "{{ gitea_service_user }}@{{ gitea_domain }}" }
    - { section: repository.signing, option: INITIAL_COMMIT, value: always }
    - { section: repository.signing, option: CRUD_ACTIONS, value: "pubkey, twofa, parentsigned" }
    - { section: repository.signing, option: WIKI, value: never }
    - { section: repository.signing, option: MERGES, value: "pubkey, twofa, basesigned, commitssigned" }

    - section: repository
      option: DEFAULT_REPO_UNITS
      value: "repo.code,repo.releases,repo.issues,repo.pulls,repo.wiki,repo.projects,repo.packages"
    - { section: repository, option: ROOT, value: "{{ gitea_repository_root_directory }}" }

    - { section: git, option: HOME_PATH, value: "{{ gitea_git_home_directory }}" }
