---
dependency:
    name: galaxy
    enabled: true
    options:
        ignore-certs: false
        ignore-errors: false
        role-file: requirements.yml
        requirements-file: requirements.yml
driver:
    name: docker
platforms:
    - name: debian_role_linux_patching_docker
      hostname: debian_role_linux_patching_docker
      image: "docker.io/library/debian:bookworm"
      pre_build_image: true
      volumes:
          - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      privileged: true
      provider_raw_config_args:
          - "--sysctl"
provisioner:
    name: ansible
    playbooks:
        converge: converge.yml
    vvv: false
    env:
        ANSIBLE_VERBOSITY: 1
    inventory:
        group_vars:
            all:
                ansible_python_interpreter: /usr/bin/python3
                linux_patching_rv_install_devel_packages: false
scenario:
    name: role.linux_patching.docker
    converge_sequence:
        - converge
    destroy_sequence:
        - destroy
    create_sequence:
        - dependency
        - create
    test_sequence:
        - syntax
        - destroy
        - dependency
        - create
        - converge
        - idempotence
        - destroy
verifier:
    name: ansible
log: true
role_name_check: 0
