---
dependency:
    name: galaxy
    enabled: true
    options:
        ignore-certs: false
        ignore-errors: false
        role-file: requirements.yml
        requirements-file: requirements.yml
driver:
    name: docker
platforms:
    - name: debian_role_linux_patching_docker
      hostname: debian_role_linux_patching_docker
      image: "docker.io/library/debian:trixie"
      pre_build_image: true
      volumes:
          - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      privileged: true
      provider_raw_config_args:
          - "--sysctl"
provisioner:
    name: ansible
    playbooks:
        converge: converge.yml
    vvv: false
    env:
        ANSIBLE_VERBOSITY: 1
    inventory:
        group_vars:
            all:
                ansible_python_interpreter: /usr/bin/python3
                linux_patching_rv_install_devel_packages: false
                linux_patching_rv_root_ca_pem_content: |+
                    -----BEGIN CERTIFICATE-----
                    MIIKmTCCBoGgAwIBAgIUMUWnVk3W5laL9WmyLJ38uLeHyF4wDQYJKoZIhvcNAQEL
                    BQAwgZAxCzAJBgNVBAYTAklOMRQwEgYDVQQIDAtXZXN0IEJlbmdhbDEQMA4GA1UE
                    BwwHS29sa2F0YTEQMA4GA1UECgwHZWFzeWlhYzEWMBQGA1UECwwNVHJ1c3QgU2Vy
                    dmljZTEvMC0GA1UEAwwmVHJ1c3QgU2VydmljZSBST09UIEVBU1lJQUMuQ09NIDIw
                    MjYgVjEwHhcNMjYwMTA1MTUxMTE5WhcNMjcwMTA1MTUxMTE5WjA5MTcwNQYDVQQD
                    DC5UcnVzdCBTZXJ2aWNlIElOVEVSTUVESUFURSBFQVNZSUFDLkNPTSAyMDI2IFYz
                    MIIEIjANBgkqhkiG9w0BAQEFAAOCBA8AMIIECgKCBAEArZjeQgGd2ScLKQtndVHT
                    QbWs/jU6Q2AxIs8KNKG6gsg781xDvCg1NfMmlnOaK1Y7fnlVvZMd2ubKDp7YEQuV
                    FAyrklonHfLxk5vyO8MY2dNL3bCbi0ncN3P/RCLsdjVyCpJrY1FopAeioyMHsVUi
                    pt/BCfcyHHbQXCiY3kLtNDe/NTeBNdT3oSzCHsa11SiADxtDpCYrtXvejMja+oA7
                    4OYK7iXrVMSxDswxbG65zW6jv/rqx/n4a7zX7GhXkfkn4H0TIwrYl8tGbyKMlnFf
                    XdXikWDjDr3GfPK+iguSgpw6izv/Or3q/g/wN0acPpdvu1Rzp7CFcXiHG/2G6b/f
                    5ama4/4GQaONAhQXEA3fEtWV4sEnCi382huT5qgVIsWPxoJf5mwFvhvTmq8M3xIF
                    1gK9gM2vkQKBLJhBMosebL+NT7qQduWhewdL/Pc+Mf7eOt9o9tMOXsSjVr+uOIKi
                    23E9LTZiQOdFDRz2Fha9ErInmHh56kqg/wy4ol5sRenOLN/123P1ReF2AiINSheV
                    2zKj1k76K4uVSipFk8rhbI/q8UCkRStMmUwl8yC4YoGWyZjko9plsGGnKcGOp8ws
                    9QG+HFkaTnwYOkHlcBrqKgMPt85qKPuA1Nm8Jz33e5vDzfkjbiVcKFKsYtaan3NK
                    OxogdzfxmIEk2yj5YqwaUaO+mEiI+3c7tVTge5lzADQ1vu2ZST7hIIOAujoAHQI4
                    ERH1WsQS6rEHRrxJ3dDJOEoqukQkpDMdKfhGuUWmnFVOTtLKT7G7wb057Z1gmsN3
                    vmmcEVKDYn+eiy6sFacZyl3SyS0j73yVTWPbX7sfYbfTzjDzR8KMk6E54g1Z10Z/
                    0DPTj/A52AprlpZp2g7gNn/HLsl7E8nwJXhj4VENIhheyACzNfybLxA5g6m5hDug
                    L9jt7sfqU+ZEQYenbvias0cwvwXRzzdNX92/TtibxwWwCetgRHK++DQU2G+uHRPZ
                    UDFx4XpIPIluQzhgcEVyO3TKBq5ZFXugn4LmJ9GEHHZB+JFFf/5tKV1m1bjtyYAx
                    o99yQA7bNU3EMNTUXUNHwzVcT0ak6k4z3D9oR8o79Lwq3Sm67h1gooMkjzkpCFfA
                    M7sB3NQCauoZ8LY4fF8Rj0fUY7awLk0wR2O4rJe5bTLaYmE8uMOXLdnQCU5XazBH
                    ZnInMoffBFo8gijxdsaL27iuSGzoX29n8sbeUIzB2rCVYyHwxQ64QTvG0mvpNTD6
                    PFClZm8RftV/D4VFH1gSByMvLDxNk1zPb8GqNUtHTN2jTAUH2HdnYYdhpaVZK63R
                    oBr8mRAzJ9a/85bQNDtBSLCF6F+j09BryeYU1gCKMaWSXUYhGbcfFEfmuwMqiP/t
                    HQIDAQABo4IBPzCCATswOQYDVR0RBDIwMIIuVHJ1c3QgU2VydmljZSBJTlRFUk1F
                    RElBVEUgRUFTWUlBQy5DT00gMjAyNiBWMzAOBgNVHQ8BAf8EBAMCAfYwXQYDVR0l
                    BFYwVAYIKwYBBQUHAwEGCCsGAQUFBwMCBggrBgEFBQcDAwYIKwYBBQUHAwQGCCsG
                    AQUFBwMIBggrBgEFBQcDCQYKKwYBBAGCNwoDAQYKKwYBBAGCNwoDBDAPBgNVHRMB
                    Af8EBTADAQH/MB0GA1UdDgQWBBQSq74ZvHjsREg5wUdAm66+VUW6BzBfBgNVHSME
                    WDBWgBS0gzOEFQNa2eb2H06eNm+4OvkxM6EogiZUcnVzdCBTZXJ2aWNlIFJPT1Qg
                    RUFTWUlBQy5DT00gMjAyNiBWMYIUehFl3WgP5ReRxXA8NJVByhxUg/0wDQYJKoZI
                    hvcNAQELBQADggQBAIOs/LwgAk/wYeMzOHi79aFY1QFn1L2V45tDJNODv7OhHwwp
                    G0+361KHIIWpI217YfjS7v/CllALU1wli+yBE3WvWDTfwPis8Zc7vutW3UW4aIVO
                    2RSE5pW5vOIZlRV07IGgzmw397nV4WRlFrpTaiaerD7zdJZbNxrWRoOhhlTCzgr8
                    fwS8CdFAEQctABZDUlQXPue7liSGGmV2AhftX+C+sD2TE+i7P55OI7fY0sTuQYS2
                    1A0MKWvqjzsPDY2A/5i76tijH4yjrZsUZcr1Yviu5mqdL68RAFHwvwmcVwcTqhT+
                    iXxhJYEI+xByydg66pBi6MsDthSKS8G+3tDOrUY2KKQeowX9/kLwBhq9zXeZGN+v
                    xozpwMNnnKnkB0s1p1iPABmq61lF+gmKEgNS1n3FHFwRQ+AK1DbIcZHCqzpfLzj0
                    s6XCU9sPI1FbqIcDQ7NlGAI88KThbSr4Dyhh0JqkvqdODI5qG8AaUAJ0jeXmE131
                    1Kj0k7DhxnFAi4hCAiCp2EMgVJzsTAKoGmHEc9ypys05AtGBy60lb9zuxQ0Thx09
                    uHDB8ZxNiArkczY79CcGD7BN3tvYslR0RvFGevPkbgbg7hVzGsnK/2lMbvpCJaFY
                    mG72wSml6lLRqZTAXALg5F45Hnk0qKUViH9K1h4i7lG46CK87x25E/8kHr0WI7Cb
                    ORL443PqO6Hyp0iNvsubmQGjzsPF4xrOkHfEogX9v1XjJlTY+WUB5H6O1jUv8hnh
                    rlOJLxnElCQJdKCg1plcK6gT8a/rhwrSTvukw9v3c2Bx7e7cMlLp5TQfqwweA1aK
                    4bSrPcc7pf9VGJr8M5V1ES3hKrEhH3umajYgPscbXuYOHYcrybLiiBUn1F7UIRWV
                    hQbHAwY3ybLaoRpiRuPRQGb8Op4f9ZmRB1ks2wh9CdDtiJyoHJyhdgWTc9Ssnrt4
                    eG4MD9QQoFn8gSHqfghoAJulfgXpZ/KRg0R6r79ape9Od6horzGPjbJZ/WA2f/JJ
                    Ofb3Ai306cjsR7DlZrxciDQIHdQs6s6BeGQqGaV+CpeWo6ii57UH0JDAy8+waPgC
                    p21MqmzRrez+55mVb+hadc4Lvh+BTfO+at8qPPS3ArxGVDgLCcFK67TIpyRm3ew1
                    nk/qKfwvANefKSbqMAB+LZL+uM9xY3BLbMPj+wpi3mZLMOTxdcOCHxQnNXzmcXZj
                    VSZVnVCc1c9HJsgRAsZBX7uILFcqUGiiICNE6iI0dw9D+Rs5mQWqC3ToeMT7PEfD
                    O5+8TPv2EOsxhzV1C1s5rnPuzQKik1IumAzGRkOYTsgk5PO1V6wp3QWHBk6/PvPc
                    9mRQglYqPq4eW91J8mZxXF+XNVS5emuC+BlAaUM=
                    -----END CERTIFICATE-----
                    -----BEGIN CERTIFICATE-----
                    MIIKhjCCBm6gAwIBAgIUehFl3WgP5ReRxXA8NJVByhxUg/0wDQYJKoZIhvcNAQEL
                    BQAwgZAxCzAJBgNVBAYTAklOMRQwEgYDVQQIDAtXZXN0IEJlbmdhbDEQMA4GA1UE
                    BwwHS29sa2F0YTEQMA4GA1UECgwHZWFzeWlhYzEWMBQGA1UECwwNVHJ1c3QgU2Vy
                    dmljZTEvMC0GA1UEAwwmVHJ1c3QgU2VydmljZSBST09UIEVBU1lJQUMuQ09NIDIw
                    MjYgVjEwHhcNMjYwMTA1MTUwOTE4WhcNMjgwNDA5MTUwOTE4WjCBkDELMAkGA1UE
                    BhMCSU4xFDASBgNVBAgMC1dlc3QgQmVuZ2FsMRAwDgYDVQQHDAdLb2xrYXRhMRAw
                    DgYDVQQKDAdlYXN5aWFjMRYwFAYDVQQLDA1UcnVzdCBTZXJ2aWNlMS8wLQYDVQQD
                    DCZUcnVzdCBTZXJ2aWNlIFJPT1QgRUFTWUlBQy5DT00gMjAyNiBWMTCCBCIwDQYJ
                    KoZIhvcNAQEBBQADggQPADCCBAoCggQBAKfYq8sAEVMp8nBL3+vYAPZjHV1q9sFS
                    8MbcvlxLRaqbV2t1cnGKgO1lB0UoIoxttMpJh1UWI6swbOtogoHc7xNb/Dcu3XEo
                    u80pQJhccE3POOB/irdmAnNqfQbzneykjsFtCtupe3oy7RFUrst8obiYuh6YynB5
                    xe8xHvrGsKc2RBUUFKBf92gAZHi3e3jDQbljhE6Csd3zKwKoCg4Nf7UmpA5QYKOZ
                    pltDiwNiZWPcdGbG0cF/xCnrgjauT5YRFkWkuDNVziwqGilDzs2qhp7w5EWZn0dv
                    RHD5sD/gXzY56D0Yny54apGLKlKM0iri1gd9uevIJagBk2Z9sNXMuDonFQis/gVd
                    kfjWYVHM9z7jpTzAWMIxO3MqZ1Di9VL5VN4JP/ud3bxO5apULj3jeJsCBl6SuUrE
                    SnBOhbNa3fE/lJkKxL8krmmj9OgyNdQF86nKhCY7iNuzrpnoRrbqlt/PMcDD98QL
                    uupXWIKdmHfzu826rcyHV3V6g/oD7Fo5Ia0xPwsKmxVV67L1x0gPLHltUlIcANde
                    mqgYGo0qAs3oOB77N4A4S4IjePSvREWtZ8+pwUNvZcVh7J2jNTkpmfl8uiRvAhvh
                    iKQDyfsEgDSYBttptxzuJCWU/h4EXW9C7PHSnRwZvRDTNZw6EOBoEdMTUtM7ektu
                    ajEWVOwjT3uhoekKg7IafBRvfZt3YDPZqCWyxPvHQpSjKBJUaiYT0VWktftTPkr0
                    1mEBbL0cNtSzuLtJb0PfA2zlFT9PXS8OajboHKoYQTM/AvqKmKRCA2XNX1qRSFmh
                    dIRYgKpVM1ENc7Irq4l4Pylr/CrtN8kUa66DfEy5o6C464i2ml+GnC1Tz6KV+Dkw
                    RIGJu+Q1oHYoRfb7vnLP9gHvLyAZnHcvEA7QGw7qQJDllNlWLW7TWXIYadKZcF+4
                    F5Bqh7J8jqQj/hW2vswaiodcVeMGw2a/HG+WPD+qCv9nD+xZowo9LGCFfuJW05Nn
                    BfZNnB30P5aLt1lUU7mVBPMYUOwGbtoZ+NBnwQNuymqzeej5wGHjSDo9e4ljJVAx
                    OtcpOiBqEQ1udWxSVDsUBPpyE5sANZIpKiA86ISxW+7A1oRuX5k80joDCrXOFQO4
                    vIORMTYo93zuBE41mIjOluyd/bUsfrlaAFJFJVVVgBnhI95LaCsnyMpYxkBE4ZTf
                    utyUlw3y0AKN+Fjs2Zzf6hv8zWE5p5eBZgbAp0+vxmZe3iJclTFz0z+YZ2vfUSm0
                    FgUqAv78lFrdP8UscIu5iy2MTJ0yNrtWehhXao5D3PsjXwVn1PaZMYh+2tFjPTG1
                    LHpNEbKMCU4ReL214bk5JU0059/w14NRqUymef5pgtThxqsIHu16AVsCAwEAAaOB
                    1TCB0jAxBgNVHREEKjAogiZUcnVzdCBTZXJ2aWNlIFJPT1QgRUFTWUlBQy5DT00g
                    MjAyNiBWMTAOBgNVHQ8BAf8EBAMCAfYwXQYDVR0lBFYwVAYIKwYBBQUHAwEGCCsG
                    AQUFBwMCBggrBgEFBQcDAwYIKwYBBQUHAwQGCCsGAQUFBwMIBggrBgEFBQcDCQYK
                    KwYBBAGCNwoDAQYKKwYBBAGCNwoDBDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
                    BBS0gzOEFQNa2eb2H06eNm+4OvkxMzANBgkqhkiG9w0BAQsFAAOCBAEAchOi71Z8
                    1sgnUPzLrnfrVi2Wa2C6Qu0BkDAMXRE3rfE8WiHapT13K18IQ8uMJZoSpX2zQTwa
                    MQqKMkDFmZHEUpp/9HinBvi986vC029lIO/fA8WmCCn/oQRIyQ8W2To9vuT7I+40
                    p2eCkCoSuF7PXCtnsRN8cUd0o5luIlKTUJAcsnn1u960OnUD/MxcHex+Itn96Ldj
                    xSQ9AeiStWi24YRiRJeoKs2yAwdAMkPzoekxYMaKfskuLgmO1UW/eokgUIoQB5yb
                    I3x/fVwy4OiV1iVKoFoySz/jLwyYKtPGFM2ejIEbsozQruB9SlgamtYJRDzWlAg3
                    odEuo/kMLlx1GW788IVo0CIxH5B2N5biiqKkAYGe3306vmrNPkkI3yKRk7MA+B6+
                    2ThJVimBu0e4PICd43bJ52fGb0Vqkk3SaN9Hc2NhA/fJ4WObQ0RNm+B6ILfHDd8z
                    KfgEpKQSF1NfIJsN+BZ/sJVqdLJT7P6jBBfx7Yd4VkOjconYyaJbJKPax1qJkvht
                    vz6ykpEEpUTpMsa51XSFjtbsSscdnEa+MZb/0HXSutcYdUk/p8Y4keHz920EkWWr
                    ePbE9F39p4eTYGSOWykdE7gcKWwNWx6/2V3h+Q+VJxoFazvxMKOg0UQIBMF+F9dl
                    55FHtK0pskRYxKJpRpqnLthGvQ9tyXkNx59Gqkfa4IZZssiSHp3mBbFBZxsvnHyr
                    VE9ZeSPl3mfK1YWMaL+y0onhMDfd8liU/+FIgFMJbMJbpyB8CbdhBoj8KDrAad7s
                    I1ynTw9vhLUZmdIV0iKJKWAWvlbEV4FAuf4e7LA3a2skZ/qxn/Jo2u3oYcOMvJnp
                    mQrKGgI6q3uBIvZ6XvVlM7xA84T9gZz3krPUMR5LoxqdNiyktGZjq5mL2WDMJa+a
                    5hMKU2VpTleQkxoLT4xuGmNerWVrfGdfqswmQ6kxbN8IvY7aLpstO2ddPCwkBPa+
                    sfbgeKygJB8THtIzX49WQqhHDb6JW4+Lp1oFQmtHKcu+j/wxNaaGaTtH5ya7OQCc
                    e4Y8y/6RolAuMuf+ZwVSyLB2ffxc3qX0K4VzSXEhh8ZX/yR6mFxMPheSxxXtVgnJ
                    /lwpgD7KdT9WO+kTTE1AH0zYBzUyO7v3MHTacjXr1nB2tOViVcAuIuPt6iG6dlrt
                    r6TdCjvzjjfAivqTD8G1JW1UXIY51uxt34Xjbm9xNKGHChmg4axpKg/e0kapc+qa
                    +3pHsT8xSkkzfoRNv1whjb6SuXV1pjThcVi2nfgDS1BeV5R3HCdUUOxHHftQDG+Y
                    D8uCZmE8nqeqTKMRbBhyXl2pmXHYgGqSJMI3+lu3JmITKcUa6J5GvuheT0w+djzS
                    rMl6B0D9AFa+ng==
                    -----END CERTIFICATE-----

scenario:
    name: role.linux_patching.docker
    converge_sequence:
        - converge
    destroy_sequence:
        - destroy
    create_sequence:
        - dependency
        - create
    test_sequence:
        - syntax
        - destroy
        - dependency
        - create
        - converge
        - idempotence
        - destroy
verifier:
    name: ansible
log: true
role_name_check: 0
