---
- name: SSHD Hardening | Fail2ban | Assert | Test Log Level
  ansible.builtin.assert:
      that:
          - ssh_hardening_rv_fail2ban_loglevel is ansible.builtin.defined
          - ssh_hardening_rv_fail2ban_loglevel is ansible.builtin.string
          - ssh_hardening_rv_fail2ban_loglevel in [ "CRITICAL", "ERROR", "WARNING", "NOTICE", "INFO", "DEBUG" ]
      quiet: true

- name: SSHD Hardening | Fail2ban | Assert | Test Log Target
  ansible.builtin.assert:
      that:
          - ssh_hardening_rv_fail2ban_logtarget is ansible.builtin.defined
          - ssh_hardening_rv_fail2ban_logtarget is ansible.builtin.string
          - ssh_hardening_rv_fail2ban_logtarget is not ansible.builtin.none
      quiet: true

- name: SSHD Hardening | Fail2ban | Assert | Test Ban Action
  ansible.builtin.assert:
      that:
          - ssh_hardening_rv_fail2ban_banaction is ansible.builtin.defined
          - ssh_hardening_rv_fail2ban_banaction is ansible.builtin.string
          - ssh_hardening_rv_fail2ban_banaction is not ansible.builtin.none
      quiet: true

- name: SSHD Hardening | Fail2ban | Assert | Test Ban Action Multiport
  ansible.builtin.assert:
      that:
          - ssh_hardening_rv_fail2ban_banaction_multiport is ansible.builtin.defined
          - ssh_hardening_rv_fail2ban_banaction_multiport is ansible.builtin.string
          - ssh_hardening_rv_fail2ban_banaction_multiport is not ansible.builtin.none
      quiet: true

- name: SSHD Hardening | Fail2ban | Assert | Test Ban Action Allports
  ansible.builtin.assert:
      that:
          - ssh_hardening_rv_fail2ban_banaction_allports is ansible.builtin.defined
          - ssh_hardening_rv_fail2ban_banaction_allports is ansible.builtin.string
          - ssh_hardening_rv_fail2ban_banaction_allports is not ansible.builtin.none
      quiet: true

- name: SSHD Hardening | Fail2ban | Assert | Test Ignore Self
  ansible.builtin.assert:
      that:
          - ssh_hardening_rv_fail2ban_ignoreself is ansible.builtin.defined
          - ssh_hardening_rv_fail2ban_ignoreself is ansible.builtin.string
          - ssh_hardening_rv_fail2ban_ignoreself in [ "false", "true" ]
      quiet: true

- name: SSHD Hardening | Fail2ban | Assert | Test Ignore IPs
  ansible.builtin.assert:
      that:
          - ssh_hardening_rv_fail2ban_ignoreips is ansible.builtin.defined
          - ssh_hardening_rv_fail2ban_ignoreips is ansible.builtin.iterable
      quiet: true

- name: SSHD Hardening | Fail2ban | Assert | Test Ban Time
  ansible.builtin.assert:
      that:
          - ssh_hardening_rv_fail2ban_bantime is ansible.builtin.defined
          - ssh_hardening_rv_fail2ban_bantime is ansible.builtin.number
          - ssh_hardening_rv_fail2ban_bantime >= -1 and ssh_hardening_rv_fail2ban_bantime !=0
      quiet: true

- name: SSHD Hardening | Fail2ban | Assert | Test Find Time
  ansible.builtin.assert:
      that:
          - ssh_hardening_rv_fail2ban_findtime is ansible.builtin.defined
          - ssh_hardening_rv_fail2ban_findtime is ansible.builtin.number
          - ssh_hardening_rv_fail2ban_findtime > 0
      quiet: true

- name: SSHD Hardening | Fail2ban | Assert | Test Max Retry
  ansible.builtin.assert:
      that:
          - ssh_hardening_rv_fail2ban_maxretry is ansible.builtin.defined
          - ssh_hardening_rv_fail2ban_maxretry is ansible.builtin.number
          - ssh_hardening_rv_fail2ban_maxretry > 0
      quiet: true

- name: SSHD Hardening | Fail2ban | Assert | Test Destination Email
  ansible.builtin.assert:
      that:
          - ssh_hardening_rv_fail2ban_destemail is ansible.builtin.defined
          - ssh_hardening_rv_fail2ban_destemail is ansible.builtin.string
          - ssh_hardening_rv_fail2ban_destemail is not ansible.builtin.none
      quiet: true

- name: SSHD Hardening | Fail2ban | Assert | Test Sender
  ansible.builtin.assert:
      that:
          - ssh_hardening_rv_fail2ban_sender is ansible.builtin.defined
          - ssh_hardening_rv_fail2ban_sender is ansible.builtin.string
          - ssh_hardening_rv_fail2ban_sender is not ansible.builtin.none
      quiet: true

- name: SSHD Hardening | Fail2ban | Assert | Test Configuration
  ansible.builtin.assert:
      that:
          - ssh_hardening_rv_fail2ban_configuration is ansible.builtin.iterable
      quiet: true
  when:
      - ssh_hardening_rv_fail2ban_configuration is ansible.builtin.defined

- name: SSHD Hardening | Fail2ban | Assert | Test Item In Configuration
  ansible.builtin.assert:
      that:
          - item.option is ansible.builtin.defined
          - item.option is ansible.builtin.string
          - item.option is not ansible.builtin.none
          - item.value is ansible.builtin.defined
          - item.section is ansible.builtin.defined
          - item.section is ansible.builtin.string
          - item.section is not ansible.builtin.none
      quiet: true
  loop: "{{ ssh_hardening_rv_fail2ban_configuration }}"
  loop_control:
      label: "{{ item.option }}"
  when:
      - ssh_hardening_rv_fail2ban_configuration is ansible.builtin.defined

- name: SSHD Hardening | Fail2ban | Assert | Test Jail Configuration
  ansible.builtin.assert:
      that:
          - item.option is ansible.builtin.defined
          - item.option is ansible.builtin.string
          - item.option is not ansible.builtin.none
          - item.value is ansible.builtin.defined
          - item.section is ansible.builtin.defined
          - item.section is ansible.builtin.string
          - item.section is not ansible.builtin.none
      quiet: true
  loop: "{{ ssh_hardening_rv_fail2ban_jail_configuration }}"
  loop_control:
      label: "{{ item.option }}"
  when:
      - ssh_hardening_rv_fail2ban_jail_configuration is ansible.builtin.defined

- name: SSHD Hardening | Fail2ban | Assert | Test Item In Filter.d Path
  ansible.builtin.assert:
      that:
          - ssh_hardening_rv_fail2ban_filterd_path is ansible.builtin.string
          - ssh_hardening_rv_fail2ban_filterd_path is not ansible.builtin.none
      quiet: true
  when:
      - ssh_hardening_rv_fail2ban_filterd_path is ansible.builtin.defined
