---
- name: SSHD Hardening | Include Asserts | Checking platform compatibility
  ansible.builtin.fail:
      msg: "{{ ansible_system }} is not supported by this role"
  when: ansible_os_family not in ['Debian']

- name: SSHD Hardening | Prerequisite | Get system 1 PID Details
  ansible.builtin.command: ps -p 1
  register: ssh_hardening_rv_tmp_one_pid_shell_result
  changed_when: false

- name: SSHD Hardening | Prerequisite | Assume system is not in systemd
  ansible.builtin.set_fact:
      ssh_hardening_rv_init_system_systemd: "{{ ssh_hardening_rv_tmp_one_pid_shell_result.stdout_lines[1] \
          | split(' ') | last == 'systemd' }}"

- name: SSHD Hardening | Install Packages | Install openssh server
  ansible.builtin.apt:
      name:
          - openssh-server
          - openssh-sftp-server
      state: present
      update_cache: true
      install_recommends: true

- name: SSHD Hardening | Enable UFW SSH Port
  community.general.ufw:
      rule: allow
      port: "{{ ssh_hardening_rv_ssh_port }}"
      state: enabled
      proto: tcp
      comment: "Allow SSH Port, Managed by Ansible arpanrec.nebula"
  environment:
      PATH: /sbin:{{ ansible_env.PATH }}

- name: SSHD Hardening | Create config directory
  ansible.builtin.file:
      path: /etc/ssh/sshd_config.d
      state: directory
      mode: "0755"
      owner: root
      group: root
  notify:
      - SSH Hardening | Restart openssh server

- name: SSHD Hardening | Place config file
  ansible.builtin.template:
      src: templates/010-ssh-ansible.conf.j2
      dest: /etc/ssh/sshd_config.d/010-ssh-ansible.conf
      mode: "0755"
      owner: root
      group: root
  notify:
      - SSH Hardening | Restart openssh server

- name: SSHD Hardening | Start and enable sshd
  ansible.builtin.systemd_service:
      name: sshd
      state: started
      enabled: true
  register: ssh_hardening_rv_tmp_start_sshd
  failed_when: >
      ssh_hardening_rv_init_system_systemd
      and
      ssh_hardening_rv_tmp_start_sshd.failed

- name: SSHD Hardening | Include fail2ban
  ansible.builtin.import_tasks:
      file: fail2ban.yml
