---
- name: Patch Cloud System
  hosts: localhost
  become: true
  gather_facts: true
  tasks:
      - name: Patch Cloud System | Checking essential variables
        ansible.builtin.assert:
            that:
                - item is defined
                - item != None
        with_items:
            - "{{ pv_cloud_username }}"
            - "{{ pv_cloud_is_dev_machine }}"

      - name: Patch Cloud System | Linux Patching
        ansible.builtin.include_role:
            name: arpanrec.nebula.linux_patching
        vars:
            linux_patching_rv_install_devel_packages: "{{ pv_cloud_is_dev_machine }}"

      - name: Patch Cloud System | SSH Hardening
        ansible.builtin.include_role:
            name: arpanrec.nebula.ssh_hardening

      - name: Patch Cloud System | Install Docker
        ansible.builtin.include_role:
            name: geerlingguy.docker
        vars:
            docker_users:
                - "{{ pv_cloud_username }}"
