---
- name: Patch Cloud System
  hosts: cloudinit
  tasks:
      - name: Patch Cloud System | Checking essential variables
        ansible.builtin.assert:
            that:
                - item is defined
                - item != None
        with_items:
            - "{{ pv_cloud_init_user }}"
            - "{{ pv_cloud_init_group }}"
            - "{{ pv_cloud_init_authorized_keys }}"
            - "{{ pv_cloud_init_is_dev_machine }}"
            - "{{ pv_cloud_init_hostname }}"
            - "{{ pv_cloud_init_domain }}"
            - "{{ pv_cloud_init_install_docker }}"

      - name: Patch Cloud System | Linux Patching
        ansible.builtin.include_role:
            name: arpanrec.nebula.linux_patching
        vars:
            linux_patching_rv_install_devel_packages: "{{ pv_cloud_init_is_dev_machine | bool }}"
            linux_patching_rv_hostname: "{{ pv_cloud_init_hostname }}"
            linux_patching_rv_domain_name: "{{ pv_cloud_init_domain }}"

      - name: Patch Cloud System | Make sure zsh is installed
        ansible.builtin.apt:
            name: zsh
            state: present
            update_cache: true
            install_recommends: true

      - name: Patch Cloud System | Add application user
        ansible.builtin.include_role:
            name: arpanrec.nebula.user_add
        vars:
            user_add_rv_user_primary_group: "{{ pv_cloud_init_group }}"
            user_add_rv_username: "{{ pv_cloud_init_user }}"
            user_add_rv_ssh_access_public_key_content_list: "{{ lookup('ansible.builtin.file',
                pv_cloud_init_authorized_keys).splitlines() }}"
            user_add_rv_user_default_shell: "/bin/zsh"
            user_add_rv_user_nopasswd_commands: ["ALL"]
            user_add_rv_user_extra_groups: ["wheel"]

      - name: Patch Cloud System | SSH Hardening
        ansible.builtin.include_role:
            name: arpanrec.nebula.ssh_hardening

      - name: Patch Cloud System | Install Docker
        when: pv_cloud_init_install_docker | bool
        ansible.builtin.include_role:
            name: geerlingguy.docker
        vars:
            docker_users:
                - "{{ pv_cloud_init_user }}"
