---
- name: Server Workspace | Install Apps | User Home Directory
  hosts: server_workspace
  tasks:
      - name: Server Workspace | Include Role | User Apps | NodeJS
        ansible.builtin.include_role:
            name: arpanrec.nebula.nodejs
        tags:
            - nodejs
        args:
            apply:
                tags:
                    - nodejs

      - name: Server Workspace | Include Role | User Apps | Go Language
        ansible.builtin.include_role:
            name: arpanrec.nebula.go
        tags:
            - go
        args:
            apply:
                tags:
                    - go

      - name: Server Workspace | Include Role | User Apps | Oracle Java
        ansible.builtin.include_role:
            name: arpanrec.nebula.java
        tags:
            - java
        args:
            apply:
                tags:
                    - java

      - name: Server Workspace | Include Role | User Apps | Terraform
        ansible.builtin.include_role:
            name: arpanrec.nebula.terraform
        tags:
            - terraform
        args:
            apply:
                tags:
                    - terraform

      - name: Server Workspace | Include Role | User Apps | Hashicorp Vault
        ansible.builtin.include_role:
            name: arpanrec.nebula.vault
        tags:
            - vault
        args:
            apply:
                tags:
                    - vault

      - name: Server Workspace | Include Role | User Apps | Pulumi
        ansible.builtin.include_role:
            name: arpanrec.nebula.pulumi
        tags:
            - pulumi
        args:
            apply:
                tags:
                    - pulumi

      - name: Server Workspace | Include Role | User Apps | Bitwarden SDK
        ansible.builtin.include_role:
            name: arpanrec.nebula.bws
        tags:
            - bws
        args:
            apply:
                tags:
                    - bws

      - name: Server Workspace | Include Role | User Apps | Hadolint
        ansible.builtin.include_role:
            name: arpanrec.nebula.hadolint
        tags:
            - hadolint
        args:
            apply:
                tags:
                    - hadolint

      - name: Server Workspace | Include Role | User Apps | Gitleaks
        ansible.builtin.include_role:
            name: arpanrec.nebula.gitleaks
        tags:
            - gitleaks
        args:
            apply:
                tags:
                    - gitleaks

      - name: Server Workspace | Include Role | User Apps | Uv
        ansible.builtin.include_role:
            name: arpanrec.nebula.uv
        tags:
            - uv
        args:
            apply:
                tags:
                    - uv
