---
dependency:
  name: galaxy
  enabled: true
  options:
    ignore-certs: false
    ignore-errors: false
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: delegated
  provider:
    managed: false
    ansible_connection_options:
      ansible_python_interpreter: /usr/bin/python3
      ansible_connection: ssh
platforms:
  - name: debian11
provisioner:
  name: ansible
  playbooks:
    converge: ../role.ssh_hardening.default/converge.yml
    prepare: ../role.ssh_hardening.default/prepare.yml
  inventory:
    group_vars:
      all:
        ssh_hardening_rv_ssh_port: 5484
    host_vars:
      debian11:
        ansible_host: 192.168.145.128
        ansible_port: 5484
        ansible_user: user
        # ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_password: password
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        ansible_become_method: sudo
        ansible_become_user: root
        ansible_become_password: password
scenario:
  name: role.ssh_hardening.delegated
  prepare_sequence:
    - dependency
    - prepare
  destroy_sequence:
    - destroy
  converge_sequence:
    - converge
  test_sequence:
    - dependency
    - destroy
    - syntax
    - prepare
    - converge
    - idempotence
    - destroy
verifier:
  name: ansible
