---
name: Molecule Test

"on":
    push:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    code_quality:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
                  cache: "pip"
                  cache-dependency-path: .github/files/requirements-dev.txt

            - name: Cache ansible
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: |+
                  pip install -r .github/files/requirements-dev.txt
                  ansible-galaxy install -r requirements.yml

            - name: Analysing the code with ansible-lint
              run: |+
                  set -ex
                  ansible-lint

            - name: Analysing the code with yamllint
              run: |+
                  set -ex
                  yamllint .

            - name: Analysing the code with pylint
              run: |+
                  set -ex
                  pylint $(git ls-files '*.py')

            - name: Analysing the code with black
              run: |+
                  set -ex
                  black --check $(git ls-files '*.py')

            - name: Analysing the code with mypy
              run: |+
                  set -ex
                  mypy $(git ls-files '*.py')

    molecule_test_role_linux_patching:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
                  cache: "pip"
                  cache-dependency-path: .github/files/requirements-dev.txt

            - name: Cache ansible
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: |+
                  pip install -r .github/files/requirements-dev.txt

            - name: Run Molecule Test
              run: |+
                  molecule test -s role.linux_patching.default

    molecule_test_role_user_add:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
                  cache: "pip"
                  cache-dependency-path: .github/files/requirements-dev.txt

            - name: Cache ansible
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: |+
                  pip install -r .github/files/requirements-dev.txt

            - name: Run Molecule Test
              run: |+
                  molecule test -s role.user_add.default

    molecule_test_role_code:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
                  cache: "pip"
                  cache-dependency-path: .github/files/requirements-dev.txt

            - name: Cache ansible
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: |+
                  pip install -r .github/files/requirements-dev.txt

            - name: Run Molecule Test
              run: |+
                  molecule test -s role.code.default

    molecule_test_role_java:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
                  cache: "pip"
                  cache-dependency-path: .github/files/requirements-dev.txt

            - name: Cache ansible
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: |+
                  pip install -r .github/files/requirements-dev.txt

            - name: Run Molecule Test
              run: |+
                  molecule test -s role.java.default

    molecule_test_role_themes:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
                  cache: "pip"
                  cache-dependency-path: .github/files/requirements-dev.txt

            - name: Cache ansible
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: |+
                  pip install -r .github/files/requirements-dev.txt

            - name: Run Molecule Test
              run: |+
                  molecule test -s role.themes.default

    molecule_test_role_terminal:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
                  cache: "pip"
                  cache-dependency-path: .github/files/requirements-dev.txt

            - name: Cache ansible
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: |+
                  pip install -r .github/files/requirements-dev.txt

            - name: Run Molecule Test
              run: |+
                  molecule test -s role.terminal.default

    molecule_test_role_go:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
                  cache: "pip"
                  cache-dependency-path: .github/files/requirements-dev.txt

            - name: Cache ansible
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: |+
                  pip install -r .github/files/requirements-dev.txt

            - name: Run Molecule Test
              run: |+
                  molecule test -s role.go.default

    molecule_test_role_nodejs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
                  cache: "pip"
                  cache-dependency-path: .github/files/requirements-dev.txt

            - name: Cache ansible
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: |+
                  pip install -r .github/files/requirements-dev.txt

            - name: Run Molecule Test
              run: |+
                  molecule test -s role.nodejs.default

    molecule_test_role_bws:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
                  cache: "pip"
                  cache-dependency-path: .github/files/requirements-dev.txt

            - name: Cache ansible
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: |+
                  pip install -r .github/files/requirements-dev.txt

            - name: Run Molecule Test
              run: |+
                  molecule test -s role.bws.default

    molecule_test_role_bitwarden_desktop:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
                  cache: "pip"
                  cache-dependency-path: .github/files/requirements-dev.txt

            - name: Cache ansible
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: |+
                  pip install -r .github/files/requirements-dev.txt

            - name: Run Molecule Test
              run: |+
                  molecule test -s role.bitwarden_desktop.default

    molecule_test_role_mattermost_desktop:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
                  cache: "pip"
                  cache-dependency-path: .github/files/requirements-dev.txt

            - name: Cache ansible
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: |+
                  pip install -r .github/files/requirements-dev.txt

            - name: Run Molecule Test
              run: |+
                  molecule test -s role.mattermost_desktop.default

    molecule_test_role_gnome:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
                  cache: "pip"
                  cache-dependency-path: .github/files/requirements-dev.txt

            - name: Cache ansible
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: |+
                  pip install -r .github/files/requirements-dev.txt

            - name: Run Molecule Test
              run: |+
                  molecule test -s role.gnome.default

    molecule_test_role_postman:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
                  cache: "pip"
                  cache-dependency-path: .github/files/requirements-dev.txt

            - name: Cache ansible
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: |+
                  pip install -r .github/files/requirements-dev.txt

            - name: Run Molecule Test
              run: |+
                  molecule test -s role.postman.default

    molecule_test_role_telegram_desktop:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
                  cache: "pip"
                  cache-dependency-path: .github/files/requirements-dev.txt

            - name: Cache ansible
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: |+
                  pip install -r .github/files/requirements-dev.txt

            - name: Run Molecule Test
              run: |+
                  molecule test -s role.telegram_desktop.default

    molecule_test_role_ssh_hardening:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
                  cache: "pip"
                  cache-dependency-path: .github/files/requirements-dev.txt

            - name: Cache ansible
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: |+
                  pip install -r .github/files/requirements-dev.txt

            - name: Run Molecule Test
              run: |+
                  molecule test -s role.ssh_hardening.default

    molecule_test_role_get_certificate_ownca:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
                  cache: "pip"
                  cache-dependency-path: .github/files/requirements-dev.txt

            - name: Cache ansible
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: |+
                  pip install -r .github/files/requirements-dev.txt

            - name: Run Molecule Test
              run: |+
                  molecule test -s role.get_certificate_ownca.default

    molecule_test_role_terraform:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
                  cache: "pip"
                  cache-dependency-path: .github/files/requirements-dev.txt

            - name: Cache ansible
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: |+
                  pip install -r .github/files/requirements-dev.txt

            - name: Run Molecule Test
              run: |+
                  molecule test -s role.terraform.default

    molecule_test_role_vault:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
                  cache: "pip"
                  cache-dependency-path: .github/files/requirements-dev.txt

            - name: Cache ansible
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: |+
                  pip install -r .github/files/requirements-dev.txt

            - name: Run Molecule Test
              run: |+
                  molecule test -s role.vault.default

    molecule_test_role_pulumi:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
                  cache: "pip"
                  cache-dependency-path: .github/files/requirements-dev.txt

            - name: Cache ansible
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: |+
                  pip install -r .github/files/requirements-dev.txt

            - name: Run Molecule Test
              run: |+
                  molecule test -s role.pulumi.default
