---
name: isort

"on":
    workflow_dispatch:
    pull_request:
        paths:
            - "**.py"
            - ".github/workflows/isort.yml"
            - "uv.lock"
            - "pyproject.toml"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    UV_FROZEN: "true"
    UV_MANAGED_PYTHON: "true"

jobs:
    isort:
        timeout-minutes: 60
        runs-on: ubuntu-24.04
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.11", "3.12", "3.13"]
        name: isort
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: Install uv 0.8.14
              uses: astral-sh/setup-uv@v6.6.0
              with:
                  version: 0.8.14
                  python-version: "${{ matrix.python-version }}"
                  enable-cache: true
                  cache-suffix: python-${{ matrix.python-version }}
                  cache-dependency-glob: |
                      **/uv.lock

            - name: Install dependencies
              run: |+
                  uv run python --version
                  uv sync --extra dev
              env:
                  UV_PYTHON: ${{ matrix.python-version }}

            - name: Analyzing the code with isort
              run: uv run isort \
                  --check-only $(git ls-files '*.py')
              env:
                  UV_PYTHON: ${{ matrix.python-version }}
