---
name: Molecule Test Role Linux Patching

"on":
    workflow_dispatch:
    pull_request:
        paths:
            - "!roles/linux_patching/README.md"
            - ".github/workflows/molecule_test_role_linux_patching.yml"
            - "meta/**"
            - "molecule/role.linux_patching.docker/**"
            - "poetry.lock"
            - "requirements.yml"
            - "roles/linux_patching/**"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    molecule_test_role_linux_patching:
        timeout-minutes: 60
        cancel-timeout-minutes: 60
        runs-on: ubuntu-24.04
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.11", "3.12", "3.13"]
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: Install poetry 2.0.1
              run: pipx install poetry==2.0.1

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5.3.0
              with:
                  python-version: "${{ matrix.python-version }}"
                  cache: "poetry"
                  cache-dependency-path: poetry.lock

            - name: Cache ansible
              uses: actions/cache@v4.1.2
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-py.${{ matrix.python-version }}-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: poetry install --with dev

            - name: Run Molecule Test
              run: poetry run molecule test -s role.linux_patching.docker
