---
name: Molecule Test Role Themes

"on":
    workflow_dispatch:
    pull_request:
        paths:
            - "!roles/themes/README.md"
            - ".github/workflows/molecule_test_role_themes.yml"
            - "meta/**"
            - "molecule/role.themes.docker/**"
            - "uv.lock"
            - "requirements.yml"
            - "roles/themes/**"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    UV_MANAGED_PYTHON: "true"
    UV_LOCKED: "true"

jobs:
    molecule_test_role_themes:
        timeout-minutes: 60
        runs-on: ubuntu-24.04
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.11.13", "3.12.11", "3.13.7"]
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: Install uv 0.8.14
              uses: astral-sh/setup-uv@v6.6.0
              with:
                  version: 0.8.14
                  python-version: "${{ matrix.python-version }}"
                  enable-cache: true
                  cache-suffix: python-${{ matrix.python-version }}
                  cache-dependency-glob: |
                      **/uv.lock

            - name: Cache ansible
              uses: actions/cache@v4.2.2
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-py.${{ matrix.python-version }}-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: |+
                  uv run python --version
                  uv sync --extra dev
              env:
                  UV_PYTHON: ${{ matrix.python-version }}

            - name: Run Molecule Test
              run: uv run molecule test -s role.themes.docker
              env:
                  UV_PYTHON: ${{ matrix.python-version }}
