---
name: Molecule Test Role BWS

"on":
    push:
        paths:
            - "!roles/bws/README.md"
            - ".github/workflows/molecule_test_role_bws.yml"
            - "meta/**"
            - "molecule/role.bws.docker/**"
            - "plugins/lookup/version_db.py"
            - "plugins/module_utils/__init__.py"
            - "plugins/module_utils/py.typed"
            - "plugins/module_utils/version_db/__init__.py"
            - "plugins/module_utils/version_db/bws.py"
            - "plugins/module_utils/version_db/grs.py"
            - "plugins/module_utils/version_db/models.py"
            - "plugins/module_utils/version_db/py.typed"
            - "poetry.lock"
            - "requirements.yml"
            - "roles/bws/**"
    workflow_dispatch:
    pull_request:
        paths:
            - "!roles/bws/README.md"
            - ".github/workflows/molecule_test_role_bws.yml"
            - "meta/**"
            - "molecule/role.bws.docker/**"
            - "plugins/lookup/version_db.py"
            - "plugins/module_utils/__init__.py"
            - "plugins/module_utils/py.typed"
            - "plugins/module_utils/version_db/__init__.py"
            - "plugins/module_utils/version_db/bws.py"
            - "plugins/module_utils/version_db/grs.py"
            - "plugins/module_utils/version_db/models.py"
            - "plugins/module_utils/version_db/py.typed"
            - "poetry.lock"
            - "requirements.yml"
            - "roles/bws/**"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    molecule_test_role_bws:
        timeout-minutes: 60
        cancel-timeout-minutes: 60
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.11", "3.12", "3.13"]
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: Install poetry 1.8.5
              run: pipx install poetry==1.8.5

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5.3.0
              with:
                  python-version: "${{ matrix.python-version }}"
                  cache: "poetry"
                  cache-dependency-path: poetry.lock

            - name: Cache ansible
              uses: actions/cache@v4.1.2
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-py.${{ matrix.python-version }}-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: poetry install --with dev

            - name: Run Molecule Test
              run: poetry run molecule test -s role.bws.docker
