---
name: Molecule Test Role SSH Hardening

"on":
    workflow_dispatch:
    pull_request:
        paths:
            - "!roles/ssh_hardening/README.md"
            - ".github/workflows/molecule_test_role_ssh_hardening.yml"
            - "meta/**"
            - "molecule/role.ssh_hardening.docker/**"
            - "uv.lock"
            - "requirements.yml"
            - "roles/ssh_hardening/**"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    molecule_test_role_ssh_hardening:
        timeout-minutes: 60
        runs-on: ubuntu-24.04
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.11", "3.12", "3.13"]
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: Install uv and set the python version
              uses: astral-sh/setup-uv@v6.6.0
              with:
                  python-version: ${{ matrix.python-version }}
                  enable-cache: true

            - name: Cache ansible
              uses: actions/cache@v4.2.2
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-py.${{ matrix.python-version }}-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: uv sync --extra dev

            - name: Run Molecule Test
              run: uv run molecule test -s role.ssh_hardening.docker
