---
name: Molecule Test Role hadolint

"on":
    workflow_dispatch:
    pull_request:
        paths:
            - "!roles/hadolint/README.md"
            - ".github/workflows/molecule_test_role_hadolint.yml"
            - "meta/**"
            - "molecule/role.hadolint.docker/**"
            - "plugins/lookup/version_db.py"
            - "plugins/module_utils/__init__.py"
            - "plugins/module_utils/py.typed"
            - "plugins/module_utils/version_db/__init__.py"
            - "plugins/module_utils/version_db/hadolint.py"
            - "plugins/module_utils/version_db/models.py"
            - "plugins/module_utils/version_db/py.typed"
            - "uv.lock"
            - "requirements.yml"
            - "roles/hadolint/**"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    UV_MANAGED_PYTHON: "true"
    UV_LOCKED: "true"

jobs:
    molecule_test_role_hadolint:
        timeout-minutes: 60
        runs-on: ubuntu-24.04
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.11.13", "3.12.11", "3.13.7"]
        steps:
            - name: Checkout
              uses: actions/checkout@v5.0.0

            - name: Install uv 0.8.14
              uses: astral-sh/setup-uv@v7.0.0
              with:
                  version: 0.8.14
                  python-version: "${{ matrix.python-version }}"
                  enable-cache: true
                  cache-suffix: python-${{ matrix.python-version }}
                  cache-dependency-glob: |
                      **/uv.lock

            - name: Cache ansible
              uses: actions/cache@v4.3.0
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-py.${{ matrix.python-version }}-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: |+
                  uv run python --version
                  uv sync --extra dev
              env:
                  UV_PYTHON: ${{ matrix.python-version }}

            - name: Run Molecule Test
              run: uv run molecule test -s role.hadolint.docker
              env:
                  UV_PYTHON: ${{ matrix.python-version }}
