---
name: "Mypy: Static Typing for Python"

"on":
    workflow_dispatch:
    pull_request:
        paths:
            - "**.py"
            - ".github/workflows/mypy.yml"
            - "uv.lock"
            - "pyproject.toml"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    mypy:
        timeout-minutes: 60
        runs-on: ubuntu-24.04
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.11", "3.12", "3.13"]
        name: mypy
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: Install uv and set the python version
              uses: astral-sh/setup-uv@v6.6.0
              with:
                  python-version: ${{ matrix.python-version }}
                  enable-cache: true

            - name: Install dependencies
              run: uv sync --extra dev

            - name: Analyzing the code with mypy
              run: uv run mypy $(git ls-files '*.py')
