---
name: Release
"on":
  push:
    branches:
      - release

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache-dependency-path: .github/files/package-lock.json

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: .github/files/requirements.txt

      - name: Install python dependencies
        run: |+
          python -m pip install --upgrade pip wheel setuptools poetry
          poetry export --without-hashes --format=requirements.txt --with dev > .github/files/requirements.txt
          pip install -r .github/files/requirements.txt
          if [ -f requirements.yml ]; then ansible-galaxy install -r requirements.yml; fi

      - name: Install node dependencies
        run: |+
          npm i semantic-release \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator \
            @semantic-release/changelog \
            @semantic-release/exec \
            @semantic-release/git \
            @semantic-release/github -D

      - name: Release
        run: npx semantic-release --extends ./.github/files/release.config.js && ls -al
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
