---
minio_systemd_service_name: "minio-{{ minio_cluster_name }}"

minio_executable: /usr/local/bin/minio-{{ minio_version_details.version }}
minio_client_executable: /usr/local/bin/mc

mini_gpg_key: |+
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    mQINBFaNnlcBEADS4E2HTkMNBg3C9zEtzyoMY/+NK4+Rb8OpDmin5YKpRLDPUq+s
    ZleNpp4mZ9dKzEGZyKmGqQ0j+PKrHm86PsFEgJcqn07Q0uMbi3kDT1leIVTmQg26
    yJI2sMtJVGVDlsEIf3fXVt9c9tQsxT9t9k9qlV3Q3dNHXPFdny2F2O7A1Jp6XOCP
    7O3lRvOUet6VeCPEFHJDM7YE8aQdNowyDzhm1tPM0C/jm/vU04ilmA31ljbUCPUl
    1F4Y1Iztwd6hmqvjdvS52AhtfM/oTkIHb5lwEjtkYBg90sbXJPsmewHIsXKjmU60
    jcDZDIUXD/6KI8ggcGe5I7aDfDeMhwVLcrHBHSXQOlJbjmHKNKZLqOwf+Xlc06ke
    Zdd0li1dxcRAidbsDMcx3TjRtDjhHvcE/UGq0C0lCnruJ9/lBtfF4fclkrvANCq+
    QL0zHHGdnb4knTKcstTqLJg3pGjvfpY2+YY+p38vqtC8XTBGDNSbLZKNQMCKOTCY
    Go7kZx2xIoF29zmzpSxD59Q9ei5rpWLphQPcDQxxDTpeQB2LQM/NIKTPkqC45W0j
    mS0y4hfs+AJx56ME4rSZ8u6q8qt14z69r9ltLLhLOBB0y66cDts1YAgSTqiC1SCH
    qs2D92N/bzFEFk0gQZzy5P8Ca5fRVD0XCgSi0XzRiHS28IPrfxs20XmIpwARAQAB
    tCBNaW5pbyBUcnVzdGVkIDx0cnVzdGVkQG1pbmlvLmlvPokCVQQTAQoAPwIbAwYL
    CQgHAwIGFQgCCQoLBBYCAwECHgECF4AWIQREBfPw3bobnmijHSUSx0OQ+arHKAUC
    ZZjpuwUJFK7l5AAKCRASx0OQ+arHKEyYEAC4Az5jDSrRkfhZ8aoZCE01Q4IM0Bvd
    LIW+UTfgub99pa3smBL2JGeAkMSeBR2Pkf7U3K6m/QJnpI5de+RSB9wZqsdjjjpG
    Jzv/BRfK4ZIlORgaC+RiCxpAIeXh2G3zDtYsmyIRXL4I9h0gNwxjb+awgHhkGkUM
    1SCLRERSOwWXrR+UnK2zbP+vS70QlAkT+NgJLSyNwoxYDAUIvHIaOSBbUL2Eqfrf
    YQP+krrTQql59+kIuBk3GEoe6Le+xHi6HLORY5eWUM8n0sFQWfuOTR64eMKF0enS
    HKp7SVyQLGUoR6LtoUw/YcZSYXw1jPEnjmK5Diwd8/ioFehL0inVxSnwSXORL2hw
    RTAqrLdGMI/3cjdEY7/ZJ+gqx8o5RCscR7UmgYHzgAFHVAriShY63ZHfi1F2L+vp
    OsAEQe92GfuvWQW5yq6nJtdM3u/UkOpkXWs2++mqfsskLkmDL5pqNMq7EVb1VGQ+
    DQ2F5BFNxUj4J/8XL642emXCod4t1KxDl/95yhBdYdsHI21pN9xj5Xo9L09XPPbd
    hgq2nKRt0wp726y8edfsdtI/ryYb3dl3EZGULAv4KQHQ6F9x+SuH3XeCANbTXfQM
    mSlTWXZ/LvUFV4s8UV+PKX2cK2jKv59xiglvQCGuGtk9AY22ryhfjnnCh5v2FLEE
    xxl3zo+L0k6va4kCVQQTAQoAPwIbAwYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AW
    IQREBfPw3bobnmijHSUSx0OQ+arHKAUCYdNI8QUJDwgRmgAKCRASx0OQ+arHKG1Y
    EACTnofNfZyfb6D18h6kzBDVPDUdNFjZ6gAhyxG+R4Gmi1v4mmVUWxO/bal9afAS
    qWUAMQkFbEBAoHis3ttTrH1e5/K5mD1ZQdcNewtDxzPkk+5AI76ffXIyfH/swTX4
    lB22XEQvtd31J5ylSIwg+AGDHLJJnUi9BWg+iTCc7f751ZfupClCIPAjABHnq2CG
    +dVkl3fzDC1RiKe+Az8aKSilkaCMkah7xlTO9AZzhaQEOOX/w5yQRMTtRtF5K8i7
    QFrm5kdVvXUMQQOEr7ElzHtHWNGU53WvkD1opLeQEZhWRubzRNb8FG1SAHcZpAH1
    upR+R5ObWTq5Hkm5J7f+Dr3onuaeh0TXxVvJAq6uH61N+xvM4bbcM8mnthNJOKMe
    gCJNl1wzHW4VC4c72VaD7UB53hY3H7mZOX4yB7Jtnc6X6QHVKZUFKMx8y+S8FN1a
    ZjEXbLoK1L5HuISD0ofHOOUIj3qvrkLXqeqKTsEZBW68lhipyQsDF+l0lguVnHG7
    KG+mZZmkvPPA4Y3+U3vtrZnftk0vADOaBhgpbINqgLgOd9jNfzKcefqoXtLP1JNx
    XiyXaO8XS1M0cNvDHd70g66MFAoKvOQslXs4K9Fptdb8zVcbkjyJyK5a/7yw+rk5
    bF98G92rvIdfejQolmXvIl1e78NujCTilNgT8CMalmwiCokCVQQTAQIAPwIbAwYL
    CQgHAwIGFQgCCQoLBBYCAwECHgECF4AWIQREBfPw3bobnmijHSUSx0OQ+arHKAUC
    XjCe8wUJC2VnnAAKCRASx0OQ+arHKPWBD/0WWfkdC1Lm/50sk4a2WNEEa4eAlQhc
    DhQCCP2egv1pO78oKPTuXGaQmpe6Eb600v7l02RUFWiHQJncHKjXFrMD3dOgLpcm
    uJVWfUlLktwDMk7Iw9bvaJs7SoU4Sg2kfHzcttq+9VIXiCGqZ4OBTqF3UfZQSz2Y
    rAq78jjh4/en5Sj1wWw68tzoEeRWLNw2UX3AIrRlB67FYRjG6rF95kciPpBhdE7G
    8v6Ca5u2PkMTrpnkGe5uW8c7InaDioEm9XDxfctB6lMROM17d1bbxIp+WCJ8v3Qx
    5lS6BJ8ao0gyS1BMbnWs1O0z7NwCUQg+BjShdVPxzGqYVxUW9YdR0H0qP9uYaSeF
    NKB/CRofX7wXXr7u+4YHkI0UsXqy5lcCisBrW41FlGeIwLgc5qZ/uDO6AhXtlL9X
    94EJ/L4u38hpGpPLcySSmXG8qFSW2i1PI5yd1lo9dwjqUwxpEC9UPGO/+MelyzCc
    BNb3qXtTBqK4M3ocHk09RxT1jIIexD9j25FSNtkNNSk6l1rEdj0BPY9o6Uy1wIVA
    FkMb5Fpv+65Y7tbHUouiOe+07bip6dCw+own78o0B+pCamQa9mC8Oiv8bm0Ib91k
    G8E/oNJQTiDZTOQs12mcPGxhPe0TFvMQ5iONcY1dkXOu9iMv2CCoHWdtHjfR/Yw3
    YuzqtwLgXmW6vokCVQQTAQIAPwIbAwYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AW
    IQREBfPw3bobnmijHSUSx0OQ+arHKAUCXJwFkgUJB++auwAKCRASx0OQ+arHKGj7
    D/0ckSOppOoNprAG6jPMq9oiRtZHxHiAI4BXYxDpO4ZJ5BEDp3bO0WuDFFsrPy1U
    cAAL9yHh2jqIeUjTPPybmed+WenGA2CAs1pdWA447DO5Xc9YXZBbLaEms24JR6a9
    iATSJE48ZmHHPUO18bhP5hPvxxsv/LZC8YxrTxW1dYpr1eGfA5Ac0ZNyUvqWMz5x
    4z5cpmfe3pD69DIjp16VvBswPZ3T32cOORDN7qk/NZcnF2Y6rLV/DAqDVDeD3FIx
    vQPERDZSf1/wknh8RB+B/MAROTLlSTXavZ9tK1UJu+X4wDJ0imxRogIG0ON/SX1c
    heQuiwRbkUy0PmL2xw3cjAoWz+evEV6NeIJ3ojLF1pCyhRhkfPT/kzJjmO1Uyzbv
    +ODHTTVUScs4Ry4ztduki3E9quiZxsQWSt0MubwJyfZ9ujrsotfEhhA4lriP+RjU
    ivWPEE9U0tYy1zd1Y/8XLWJufRM+sm+TnfIdT+dVnSm4qxwwe4kuQRj3cU1vE43O
    +43PKLpHy/TdAhC7xywnRNlCN9pGGVC4Ao65Z1LDuiUKGE6XVujJqOZspVhlyFEQ
    09L5cEQcklopkjXf7hwTdWwtiyb7u3Muq7f6hnJ9ErcU6UOgqTpl3jR1H9UXe1Xo
    o/zbmCsIDaV5DbkyPE/fBEgXPehxIoPW3SD1P0bpLU2e9IkCPgQTAQIAKAIbAwYL
    CQgHAwIGFQgCCQoLBBYCAwECHgECF4AFAlpzjBkFCQeoVMIACgkQEsdDkPmqxyg4
    eBAAuBVV7fTcURD1TEdmU2vNcRSP9nqeTwNgJnmqey64dCNNTBy/CoYaUEyaW86Y
    r93DYy+giKHCJghjkDJ7hYMi/OyoZnCP0wTQHAoRDGMMXAgSqwslHN2DjhN4Jvm6
    RNzCQq6h0XyWI+dwDtAUzkPAN2kgs5F6HH/Clht4/AJmUK6kUn7CgWhWseyskfyp
    nOv7JekkyWDiclL+g26zFDwmXrw8xmXWjEuHmthoXHq8s7h6Jx7/pHmk/TY2IFsM
    9SGZN3eabXRgPlrXMmMrDByAq+elz3vZBwBEjWAwCw9la98yNMB2yMQOZ4DE+rbk
    uHSwHJcwgEbR892t4BZe/sveoaMkN0ZbexI+mASMW2OIr0t1nbnFek+yIuoVdcVH
    DyJUzkerIe5N5P1/n0OysVxnel0TFKct6zgTTni7uYuLWpNCsAjXFVDOMygCTkb9
    ABtl6MtgtTTrX0JPQl5cNoK5OI9tuz7LCnvMGE6GpHkiRbBcqyHjngScmBdmEaXa
    ncVnD2R2F5WdThEFY0nlgQnqQQHuxyVZJXmkGlNMWvQIVTvQiKCVTgiFQoOiQ9hw
    0M2cmfL9lG4G3uedwml+pMDicp6ZN/bI+h9UnjofoiAJKeh22Rf1SmawqFpHUj3i
    5uEnKv/0bNco8jQPG+ctSYBHv5v3C1/SIUS8fRy90lsnfEOJAj4EEwECACgCGwMG
    CwkIBwMCBhUIAgkKCwQWAgMBAh4BAheABQJYlnT0BQkD6goaAAoJEBLHQ5D5qsco
    b6IP/1eYt+Rmd5NEvvKvyuhi/fLjoEh2sOCkTstXlNZaPTYGLUIacxdaaUhZceFR
    csaA+wQHmsvPpSoCCgZLzp7jpQukaddDMXV9a6y7Cn1O0tOSGRZBIltSsXy6G5u6
    eR+fF2aO0EDNw1Mny8voXdh6ryUlcCPNm4IcACaxZAXbQSQhoDEou3xLiSBl4h/M
    QV9CTG3u02eHGOblykggs/apWutBiLDSjwYMM69DlyqE1EjwtCj3bYQuUq0t0sGk
    8R7h/ATXn4kCUQtVqYi47zIzuO8CyamOqIR5m7TKHykWFZJCaZaUzJCv7+kchS46
    RGLCABuNXlSqBTe01HYIWvtdZ5M+7p/NeNCmpbgBwNVCxbGsUHbOu45eIHzohe3L
    GxxfHRB0HgW8UY8hlhd2TDmT/sAqN1uFX+vRCwtbM9nrreuTpqSUQA18DN1m+AHp
    jGuquwMfrry3/L+lIzcviRDju2mt8FonLw39K/45yUGUUEGsXpiAvRN/mugWF2qm
    r6StdlN2tF9qA2/QX5mkIaIgipX34Ed4/EVpuEEe2KjWVkMR/a0wd3eNUGkvwdx+
    UnqD7OiaOJvGtj5QNwWJjkZTbXblDh06V9aENKghoCq9NrALaC2k+CYZepHH8rRK
    n3Zf4/1gjrXbkpfMwffpBHQWFToDCZfF9uw4HFKtRu0W5G64iQI+BBMBAgAoAhsD
    BgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAUCVrPv8AUJAgeFEwAKCRASx0OQ+arH
    KNzkEACuAi1ySz28s+mmsq4sd89K+x+OiFpniy6f4Z3asVDlaRPPcs/LsJtYU67m
    77YPXl4AYKAFpP04tXIUocQ1ajGlEsS8jfl7KowURtzxTOK5eUFzBk8X9aUeg6ZM
    NgsLI4a5c8WJNNrYQ6HcAjDpbNK8dUDtb8J+WDMdiA6QHVIT+j83gLJ64tdBAF4V
    k0N5q5bva1aLWVvJZfbOuRYuoyWVTKpRT2KEZL1CDiRN7dEFrcVRyz184k/lcwTK
    CBSj0nY0YJ399mqdn1EQWJL9MDaJfM0gJ1ninOqYz852+n/N4HYTVL4PmM5XwmAX
    MDoBKdFiHwb7c7SuPa2QhBirSmZXo7i/LToKdr7fcJq224PRIUw4DMZDubp8wtg8
    +Zls9P2cR69PjUJAylXfFvftbdbmdV2CIFusOJ3JbmkiW47n3gLXD23EywVd44fG
    4/YCEL/1Dq518h+kJcJTNZsqDtg+zHM1dd/6yJC0/Pjmkgh5sfl5AZtpIA0hEPfU
    DLK27BJ6Neg436JxIwXFpqjMKoLBzXtpYs4NYR6yz6PvDK5A9HVl7OXzE3SFFReH
    UDmu2OqQCDfRY2+/QpAbeYszBdVyzqfUB5/U5rrRg/Ub/wrt+1qH1jjG25JPMvcE
    j/CULAdrM1q9nwUQizC4J5ENo8HQVTww3+1d9e6yEeY1QuSi/YkCPgQTAQIAKAUC
    Vo2eVwIbAwUJAAKjAAYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AACgkQEsdDkPmq
    xyhPvRAAt6G/ekuYdHG5t0i2rXDG8mrmx49fVQCjSMnaWk1b6gP9KEoT5OMOLg6Z
    m9yMsGrVI/EzuybGFTNIz39Jo53qtfodq+4r/FSEMAr8C8ZKEsdbnvNW7xO95CLm
    9sKErimV3H5sUaHsBd3GTVFkciFHSdtFjPj8fdtwyOAGvsOwII9l3zxczOxLa7/u
    Bf2IN+RloEPTj3IeaVWhveBmdZegjwsbCuw9I6of4BYEDAgNXXB89ibIAL7EjSUC
    RAA99KEg+HHAx5TLsQ1Zuynjt4F5kqI/YMIFVCqOD0WFffM560zM4w9HhTXKMQpz
    TZpe7NvaHDPKkhTfyD2g//o+LRPzCv/jRSSdFnSs7cgofHpDpoLT5XfqVHw0ORfA
    OqXluULL/NwoXhYMZkmse/97N9XITsS5qgRVfafEDjB6VjcxUcfSYIE8vff2iU/K
    QWyIICLAQy8GPNkHF6FYdI2U7KWcKzCH0MloUX7pcdiyyhc3+fOlM5vTNLlMZxb5
    R7RN/qh32BI3G8+FpWeICDh/iNttMRT7A1A5NDqi3+hNK+OxunwqGIaWxooI+trB
    LuSbLGEn7PVRGbo/wsFviD0zXsEZa6vdcUh/07j2qnDLymwdGt6EJ/vLRyS8+oNw
    iJmt9sizhMJlkchHHSyY4ega/vJdeUeOPu5eAIWxGYXJsIL2FHq5Ag0EVo2eVwEQ
    AMY/x0PjVWoaQQBp0q/NO5ayNrK1Ug2s04Lzc6nvXZ41IM6qirHX+MPXViGWGMh8
    IB6xaHGZkYxAlb8ybNd7IwpC3bpIItApjgyPQjiY8q1tJoriYajfhSk3jMoxddsX
    BRZ8ouxUH1E6gzROJNctH5IzES+NFGGvG4u+TdImeYsV4a9RIYuyZOqPzzGe0O+Z
    H0swjxK/8+erIDQWYleJRLWLQTbj9QHjx7czpp8A8Y03Lh1w00GNHjDvYRkjlDSy
    5KtQ2i5d6grZ8l9ZRpM05CKtCLtUY1QFFCrS/7yAzL74v49XbmD8hetJ7AuGlUuf
    I7qAHTVJZNFxv8qz0R3Atum/fFvU5UGxh5I5l114AK4+Nl1zVOg03f9KOo1hkUp1
    BaC3hY2qzOgebHTXsnokvRGEbGyxm0K61l8hOGYQc2oKhs4mSlLrJIdpNjy76Tnj
    2bz6mJHvTPPo27UuoldA+jFklbrRZs5Sm45RqeFcKNdq9xzc93lA2IFt+q00dtxN
    cdCxgu+F/B4iyj0/qmRL93lqkgx98kHiPreVdI7ZQ4emv6NP0L2S2LKj4kG1UM9L
    WKLoyhNvsuCTFs90/wpkvHYjP14nT8Cnc1wTu29lkfFQQrtSu1NdyHSwvU1+dSm3
    Mybq74WHNN43o8mJ+bheXjdqLoFI9XsyEKtL5/29Pd4pABEBAAGJAjwEGAEKACYC
    GwwWIQREBfPw3bobnmijHSUSx0OQ+arHKAUCZZjqEwUJFK7mPAAKCRASx0OQ+arH
    KGL2D/9nL+QAYf8AN66NBMPT+Gvusesf8ik/7xzNwJnayhU5URARYMmqmLcXCZ1Q
    99GTORrs1+GN19e1AiSyG0DvH8wSfKM0qxB7cyHt1iZvhd7Lldl/RYEqgGAMgzBm
    w7Mo6fNFdtD0EBNANs76DaZMtyGKDoGacSIHhGzVHwqPtOgfujrjbT569HUROhaj
    +CIaIrkIYNcRZj8w0eQteK3VQEo8omJyQjh5SCu3Sm5K/ZYtpIBuMXAbIGYCSlUE
    h4MfpjrqpX12HUZnRFKTeXDp9/WafAsmiq/+j7GZY8wzEMblNMgr7dhuEBnk9G3D
    qKfWyFkddYPc1J9bHq3RYkgMINdimXgyxU9PthI+/mTXlVfzRCrINPZr1VRG4yOp
    s/mYvULhBjHPWbRVsXN1YguBmYFOdrdcwc6j7Lh+bE9OIH5YWlAaXEJqo9nDVym6
    QfkAo5faU6uZ7loi+/TgpADdMMTSuDGxDvbRUpWq1n+mDVCYxMDuq6AIb7SOv7vI
    DP14KWGhVxL+oo35968L9/4+QKaZASXgQcqu2fGfB8wCSR1qz0Td7uOExUWomDLT
    7pa8QHBRp0OKohc1P9N/2tPqTG6v9CYXfBFzQVXg4lUIAA+4vZXF2sLOkO+qJ8Ir
    FNOByHgRJyg5WqJXNk/NtBxXKYYnQZGlj6V9wX0cyrMZdZwuxA==
    =d7d0
    -----END PGP PUBLIC KEY BLOCK-----
